<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<module category="" descriptorversion="1.0" entrypoint="RCOM_CF_RED_IVR/Start" forcesubdialogcall="false" frameworkversion="07.01.08.04" iconlarge="icons/defaultapplicationlg.gif" iconsmall="icons/defaultapplicationsm.gif" modifyInputs="false" modifyOutputs="false" nature="com.avaya.sce.core.speechnature" outputmultipart="false" paramasnamelist="false" provider="" submitmethod="get" version="1.0.0" webname="RCOM_CF_RED_IVR">
    <description/>
    <language name="ENG" root="en-us"/>
    <language name="HIN" root="gu-in"/>
    <language name="TAM" root="en-us"/>
    <language name="TEL" root="en-us"/>
    <language name="MAL" root="en-us"/>
    <language name="KAN" root="en-us"/>
    <dependencies>
        <moduleref frameworkversion="07.01.08.04" name="DM" private="false" version="1.0.0">
            <meta callflow-references="main"/>
        </moduleref>
    </dependencies>
</module>
