package flow.subflow.CreditCardPayment;

import com.avaya.sce.runtimecommon.SCESession;
import com.servion.hsd.utils.AppConstant;
import com.servion.hsd.utils.Constants;
import com.servion.util.AppProperties;

import flow.IProjectVariables;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2015-APR-16  09:25:46 PM
 */
public class CheckResponse extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	@Override
	public void requestBegin(SCESession mySession) {
		super.requestBegin(mySession);
		
		/*Declaring variables*/
		String strInitialAudios = "";
		String strErrorCode = "";
		AppProperties appProperties = null;
		
		/*Assigning values*/
		appProperties = AppProperties.GetInstance(AppConstant.DYN_MENU);
		strErrorCode = mySession.getVariableField(IProjectVariables.POSTPAID__VALIDATE_CREDIT_CARD, IProjectVariables.POSTPAID__VALIDATE_CREDIT_CARD_FIELD_ERROR_CODE).getStringValue();
		
		/*Initializing audio*/
		if(strErrorCode.equals("1")||strErrorCode.equals("-1"))
		{
			strInitialAudios = appProperties.getIVRProp("PMT_ERR_1");//"22875.wav";
		}else if(strErrorCode.equals(Constants.ER_CODE_0001)){
			strInitialAudios = appProperties.getIVRProp("PMT_ERR_9");//"22876.wav";
		}else if(strErrorCode.equals(Constants.ER_CODE_0002)){
			strInitialAudios = appProperties.getIVRProp("PMT_ERR_2");//"22877.wav";
		}else{
			strInitialAudios = appProperties.getIVRProp("PMT_ERR_NA");//"22878.wav";
		}
		
		
		/*Setting to session*/
		mySession.getVariableField(IProjectVariables.DM_INPUT_PARAMETER, IProjectVariables.DM_INPUT_PARAMETER_FIELD_INITIAL_PROMPT).setValue(strInitialAudios);
		
		
	}
	
	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2015-APR-16  09:25:46 PM
	 */
	public CheckResponse() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2016-AUG-11  02:39:11 PM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = new com.avaya.sce.runtime.Next("CreditCardPayment-PlayResponseCode", "Default");
		next.setDebugId(1824);
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2016-AUG-11  02:39:11 PM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2016-AUG-11  02:39:11 PM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(2);
		actions.add(new com.avaya.sce.runtime.varoperations.Assign("Postpaid_CallData:transferReasonCode", "TR_0019", true).setDebugId(2457));
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
}
