<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<module category="testCategory" descriptorversion="1.0" entrypoint="RecordMessageFile/Start" forcesubdialogcall="false" frameworkversion="07.21.05.02" iconlarge="icons/defaultapplicationlg.gif" iconsmall="icons/defaultapplicationsm.gif" modifyInputs="false" modifyOutputs="false" nature="com.avaya.sce.core.speechnature" outputmultipart="false" paramasnamelist="false" provider="testVendor" submitmethod="get" version="1.0.0" webname="RecordMessageFile">
    <description/>
    <output defaultvalue="" description="" name="returnState" varreftypesimple="true"/>
    <language name="english" root="en-us"/>
    <language name="cantonese" root="zh-hk"/>
    <dependencies/>
</module>
