package flow;


import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;
import com.rcom.Data.utils.AppConstant;
import com.rcom.Data.utils.Constants;
import com.rcom.Data.utils.StackTrace;
import com.rcom.prepaid.model.MDNHotFlashInfo;
import com.rcom.prepaid.resource.IVRDBServiceInstance;
import com.servion.rcom.CDMA.hostinterface.view.ReqPushSMS;
import com.servion.rcom.CDMA.hostinterface.view.ResPushSMS;
import com.servion.rcom.CDMA.hostinterface.wrapper.IVRWebService;
import com.servion.rcom.CDMA.hostinterface.wrapper.IVRWebServiceImpl;
import com.servion.util.AppProperties;
import com.servion.util.IVRDataBean;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2016-APR-19  01:17:10 PM
 */
public class pushSMS extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2016-APR-19  01:17:10 PM
	 */
	public pushSMS() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	@Override
	public void requestBegin(SCESession mySession) {
		super.requestBegin(mySession);
		
		/*ITraceInfo trace = mySession.getTraceOutput();
	
	
		String completeSMSText = Constants.EMPTY_STRING;
		ReqPushSMS reqPushSMS = null;
		ResPushSMS resPushSMS = null;
		IVRWebService ivrWebService = null;
		String DataActDeact="";
		String strMsgText="Test sms";
		IVRDataBean objIVRDataBean = null;
		
		
		
		try{
			
			
			trace = mySession.getTraceOutput();
			objIVRDataBean = (IVRDataBean)mySession.getProperty(Constants.IVRDataBean);
			
			
			MDNHotFlashInfo mdnhost=new MDNHotFlashInfo();
			
			mdnhost.setMdn(mySession.getVariableField(IProjectVariables.SESSION, IProjectVariables.SESSION_FIELD_ANI).getStringValue());
			
			//**DB**//*
			mdnhost=IVRDBServiceInstance.getInstance().checkMDNHotFlashFlag(objIVRDataBean, mdnhost);
			
			trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG,"SMS DB Responce :"+mdnhost.toString());
			
		    String	mdn_sms=mdnhost.getP_MDN_MSG_OUT();
			
			objIVRDataBean = (IVRDataBean)mySession.getProperty(Constants.IVRDataBean);
			
			reqPushSMS=new ReqPushSMS();
			
			trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "SMS from DB:"+mdn_sms);
			
			ivrWebService = new IVRWebServiceImpl();
			
			
			
			trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "IN ANI");
			
			
			reqPushSMS.setMDN(mySession.getVariableField(IProjectVariables.SESSION, IProjectVariables.SESSION_FIELD_ANI).getStringValue());
			
			trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "After set  SMS");
			
			if (mdn_sms.equalsIgnoreCase("NA"))
			{
				strMsgText = AppProperties.GetInstance(AppConstant.IVR_SIM_CONFIG).getIVRProp("ACTIVE_SMS");
			}
			else
			{
				strMsgText = mdn_sms;
			}
			
			//strMsgText = AppProperties.GetInstance(AppConstant.IVR_SIM_CONFIG).getIVRProp("ACTIVE_SMS");
			
			trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "After set  SMS"+strMsgText);
			reqPushSMS.setMessageText(strMsgText);
			 
			
			resPushSMS = ivrWebService.executePushSMS(objIVRDataBean, reqPushSMS);
			
			trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "resPushSMS status is :"+resPushSMS);
			
		}catch (Exception e) {
			StackTrace.PrintException(e);
			trace.writeln(ITraceInfo.TRACE_LEVEL_ERROR, "Exception in sending SMS"+e);
			
		}finally{
			
			reqPushSMS = null;
			resPushSMS = null;
			ivrWebService = null;
		}*/
	}	
	
	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2017-APR-28  01:19:14 PM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = new com.avaya.sce.runtime.Next("Thankyou_SIM_PA_0002", "Default");
		next.setDebugId(6735);
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2017-APR-28  01:19:14 PM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2017-APR-28  01:19:14 PM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
}
