package flow;

import java.net.InetAddress;
import java.text.SimpleDateFormat;
import java.util.Date;

import org.apache.log4j.Logger;

import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;
import com.rcom.util.AppConstants;
import com.rcom.util.StackTrace;
import com.servion.prepaid.report.GetReportObject;
import com.servion.prepaid.report.IVRREPORTDATA;
import com.servion.prepaid.report.IVRREPORTDATA.CALLINFO;
import com.servion.util.AppProperties;
import com.servion.util.IVRDataBean;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2015-JUN-12  12:46:10 PM
 */
public class Capture_ANI_DNIS_BC extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2015-JUN-12  12:46:10 PM
	 */
	public Capture_ANI_DNIS_BC() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2016-OCT-12  02:20:51 PM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = new com.avaya.sce.runtime.Next("TechDiff_PP", "NotAvailable");
		next.setDebugId(3972);
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2016-OCT-12  02:20:51 PM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2016-OCT-12  02:20:51 PM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(4);
		com.avaya.sce.runtime.BooleanOperation bo1 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.AND);
		com.avaya.sce.runtime.Expression be1 = new com.avaya.sce.runtime.Expression("expression1", "session:ani", com.avaya.sce.runtime.Expression.NOT_EMPTY);
		bo1.addExpression(be1);
		com.avaya.sce.runtime.Expression be2 = new com.avaya.sce.runtime.Expression("expression2", "session:dnis", com.avaya.sce.runtime.Expression.NOT_EMPTY);
		bo1.addExpression(be2);
		actions.add(new com.avaya.sce.runtime.tracking.TraceInfo(com.avaya.sce.runtimecommon.ITraceInfo.TRACE_LEVEL_DEBUG, "ANI :", "session:ani").setDebugId(3962));
		actions.add(new com.avaya.sce.runtime.tracking.TraceInfo(com.avaya.sce.runtimecommon.ITraceInfo.TRACE_LEVEL_DEBUG, "DNIS :", "session:dnis").setDebugId(3963));
		actions.add(new com.avaya.sce.runtime.tracking.TraceInfo(com.avaya.sce.runtimecommon.ITraceInfo.TRACE_LEVEL_DEBUG, "Application Name", "AppName").setDebugId(3964));
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(3965)).evaluate(mySession, bo1)) {
			actions = new java.util.ArrayList(4);
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("appVariables:ani", "session:ani", false).setDebugId(3969));
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("appVariables:dnis", "session:dnis", false).setDebugId(3970));
			actions.add(new com.avaya.sce.runtime.Next("DNISRoutingHit", "Ani&Dnis").setDebugId(3971));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

		}

		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
	
	@Override
	public void requestBegin(SCESession mySession) {
		/**Declaration **/
		String sessionID = AppConstants.EMPTY_STRING,PropertyKey= AppConstants.EMPTY_STRING;
		String appName = AppConstants.EMPTY_STRING,PropertyLocation= AppConstants.EMPTY_STRING,defaultLanguage = AppConstants.EMPTY_STRING;
		Logger logger = null;
		ITraceInfo trace = null;
		IVRREPORTDATA ivrreportdata = null;
		InetAddress ip = null;
		CALLINFO callInfo  = null;
		SimpleDateFormat dateFormat = null;
		String callerType = AppConstants.EMPTY_STRING,overrideANI = AppConstants.EMPTY_STRING;
		
		/**Assign**/
		trace = mySession.getTraceOutput();
		try{
			sessionID = mySession.getSessionId();
			logger = Logger.getLogger(AppConstants.LOGGER_NAME_CALLLEVEL);
			defaultLanguage = AppProperties.GetInstance(AppConstants.IVR_CONFIG).getIVRProp(AppConstants.DefaultLanguage);
			
			appName = AppProperties.GetInstance(AppConstants.IVR_CONFIG).getIVRProp(AppConstants.APP_NAME);
			mySession.getVariableField(IProjectVariables.APP_NAME).setValue(appName);
			mySession.setProperty(IProjectVariables.APP_NAME,appName);
			
			/** Override Processing **/
			overrideANI = AppProperties.GetInstance(AppConstants.IVR_CONFIG).getIVRProp(AppConstants.OVERRIDE_ANI);
			if(!overrideANI.equalsIgnoreCase(AppConstants.N) && overrideANI !=null && !overrideANI.equalsIgnoreCase(AppConstants.EMPTY_STRING))
			{
				trace.writeln(ITraceInfo.TRACE_LEVEL_INFO, "** ANI Overriden **");
				mySession.getVariableField(IProjectVariables.SESSION, IProjectVariables.SESSION_FIELD_ANI).setValue(overrideANI);
			}
			
			//appName = mySession.getVariableField(IProjectVariables.APP_NAME).getStringValue();
			PropertyKey = AppConstants.PROPERTY+appName+AppConstants.SEPERATOR_UNDERSCORE+defaultLanguage;
			dateFormat =  new SimpleDateFormat(AppConstants.DATE_FORMAT_REPORT);
					
			trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "default Language :"+defaultLanguage);
			trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "application Name :"+appName);
			trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "Property Key :"+PropertyKey);
			
			/**Create IVR Bean Object**/
			IVRDataBean objIVRDataBean = new IVRDataBean(); 
			trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "Session ID :"+sessionID);
			objIVRDataBean.setLogger(logger);
			objIVRDataBean.setSessionID(sessionID);
			
			
			/**Default Property File Location**/
			
			PropertyKey = AppConstants.PROPERTY+appName+AppConstants.SEPERATOR_UNDERSCORE+defaultLanguage;
			
			trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "default Language :"+defaultLanguage);
			trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "application Name :"+appName);
			trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "Property Key :"+PropertyKey);
			
			PropertyLocation = AppProperties.GetInstance(AppConstants.IVR_CONFIG).getIVRProp(PropertyKey);
			trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "Property Location :"+PropertyLocation);
			
			if(PropertyLocation!=null && PropertyLocation!="N")
				mySession.getVariableField(IProjectVariables.DM__INPUT_PATH,IProjectVariables.DM__INPUT_PATH_FIELD_DM__PROPERTIES_LOCATION).setValue(PropertyLocation);
			else{
				trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG,"properties Location is Null");
				PropertyLocation = AppProperties.GetInstance(AppConstants.IVR_CONFIG).getIVRProp(AppConstants.DEFAULT_PROPERTY_LOCATION);
				trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG,"default properties Location :"+PropertyLocation);
				mySession.getVariableField(IProjectVariables.DM__INPUT_PATH,IProjectVariables.DM__INPUT_PATH_FIELD_DM__PROPERTIES_LOCATION).setValue(PropertyLocation);
			}

			if(appName!=null && appName.contains(AppConstants.CDMA)){
				callerType = AppConstants.CDMA;
			}else{
				callerType = AppConstants.GSM;
			}
			
			trace.writeln(ITraceInfo.TRACE_LEVEL_INFO,"Caller Type :"+callerType);
			mySession.getVariableField(IProjectVariables.APP_VARIABLES,IProjectVariables.APP_VARIABLES_FIELD_CALLER_TYPE).setValue(callerType);
			
			/**Reporting**/
			GetReportObject objGetReportObject = new GetReportObject();
			objGetReportObject.createIVRReportObject();
			objIVRDataBean.setGetReportObject(objGetReportObject);
			mySession.setProperty(AppConstants.IVRDATABEAN,objIVRDataBean);
			
			ivrreportdata = objGetReportObject.createIVRReportObject();
			mySession.setProperty(AppConstants.BEANREPORTDATA, objGetReportObject);
			objGetReportObject.setIvrreportdata(ivrreportdata);
			objIVRDataBean.setGetReportObject(objGetReportObject);
			
			/**Assigning call info data for report*/
			trace.writeln(ITraceInfo.TRACE_LEVEL_INFO,"/*** Call Info Reporting is started ***/");
			ip= InetAddress.getLocalHost();
			callInfo  = ivrreportdata.getCALLINFO();
			callInfo.setUNIQUECALLID(mySession.getVariableField(IProjectVariables.SESSION, IProjectVariables.SESSION_FIELD_UCID).getStringValue());
			callInfo.setSESSIONID(mySession.getSessionId());
			callInfo.setVXMLIP(String.valueOf(ip));
			callInfo.setSTARTDATETIME(dateFormat.format(new Date()));
			callInfo.setAPPNAME(appName);
			callInfo.setCALLERTYPE(callerType);
			callInfo.setCATEGORY(AppConstants.NA);
			callInfo.setCIRCLEID(AppConstants.NA);
			callInfo.setCLI(mySession.getVariableField(IProjectVariables.SESSION, IProjectVariables.SESSION_FIELD_ANI).getStringValue());
			callInfo.setDNIS(mySession.getVariableField(IProjectVariables.SESSION, IProjectVariables.SESSION_FIELD_DNIS).getStringValue());
			callInfo.setDNISTYPE(AppConstants.NA);
			callInfo.setHUB(AppProperties.GetInstance(AppConstants.IVR_CONFIG).getIVRProp(AppConstants.HUB));
			callInfo.setAGENTID(AppConstants.NA);
			callInfo.setAGENTEXTN(AppConstants.NA);
			callInfo.setTRANSCODE(AppConstants.NA);
			callInfo.setTRANSCODE(AppConstants.NA);
			callInfo.setLANGUAGEFROM(AppConstants.NA);
			callInfo.setLANGUAGETO(AppConstants.NA);
			callInfo.setTAGGING(AppConstants.NA);
			callInfo.setTRANSFERVDN(AppConstants.NA);
			callInfo.setUUIDATA(AppConstants.NA);
			callInfo.setABANDONEDFLAG(AppConstants.NA);
			callInfo.setTRANSTOIVR(AppConstants.NA);
			callInfo.setSKILLNAME(AppConstants.NA);
			callInfo.setLANGCODE(AppConstants.ENG);
			callInfo.setENDDATETIME(AppConstants.NA);
			callInfo.setDTMFPATH(AppConstants.NA);
			callInfo.setMENUPATH(AppConstants.NA);
			callInfo.setCALLERPATH(AppConstants.NA);
			callInfo.setLASTMENUACCESSED(AppConstants.NA);
			callInfo.setDISPOSITION(AppConstants.ID);
			callInfo.setCALLENDREASON(AppConstants.IVR_DISCONNECT);
			callInfo.setHOWCALLENDED(AppConstants.DISCONNECT);
			callInfo.setERRREASON(AppConstants.NA);
			ivrreportdata.setCALLINFO(callInfo);
			
			objIVRDataBean.setGetReportObject(objGetReportObject);
			/**Setting Bean in Session **/
			mySession.setProperty(AppConstants.IVRDATABEAN,objIVRDataBean);
		}catch(Exception e){
			trace.writeln(ITraceInfo.TRACE_LEVEL_ERROR,"ERROR in Call Start :"+e);
			StackTrace.PrintException(e);
		}	
	}
}
