package flow;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2015-JUN-18  03:18:36 PM
 */
public class CheckKnowCallerMenu extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2015-JUN-18  03:18:36 PM
	 */
	public CheckKnowCallerMenu() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2016-SEP-28  04:13:56 PM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = null;
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2016-SEP-28  04:13:56 PM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2016-SEP-28  04:13:56 PM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition1", "KnowCaller_MN:ReturnCode", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "constants:success", true).setDebugId(9395)).evaluate(mySession)) {

			if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition2", "KnowCaller_MN:Value", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "constants:GPMR_Repeat", true).setDebugId(12067)).evaluate(mySession)) {

				if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition3", "appVariables:tries", com.avaya.sce.runtime.Expression.STRING_EQUAL, "constants:Three", true).setDebugId(12068)).evaluate(mySession)) {
					actions = new java.util.ArrayList(2);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("appVariables:transferCode", "TransferCodes:DAKC_TR_0010", false).setDebugId(12069));
					actions.add(new com.avaya.sce.runtime.Next("RepeatTriesExceeded_PP", "(Repeat Tries Exceeded)").setDebugId(12070));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				} else {
					actions = new java.util.ArrayList(2);
					actions.add(new com.avaya.sce.runtime.varoperations.Increment("appVariables:tries").setDebugId(12072));
					actions.add(new com.avaya.sce.runtime.Next("KnowCaller_MN", "(Repeat)").setDebugId(12073));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;
				}


			}


			if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition4", "KnowCaller_MN:Value", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "constants:KnowCallerMenu_RetVal_PostpaidCustomer", true).setDebugId(9398)).evaluate(mySession)) {
				actions = new java.util.ArrayList(2);
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("appVariables:tries", "constants:One", false).setDebugId(9702));
				actions.add(new com.avaya.sce.runtime.Next("KnowCaller_PC", "(Existing Postpaid Customer)").setDebugId(9399));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition5", "KnowCaller_MN:Value", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "constants:KnowCallerMenu_RetVal_PrepaidCustomer", true).setDebugId(9400)).evaluate(mySession)) {
				actions = new java.util.ArrayList(2);
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("appVariables:tries", "constants:One", false).setDebugId(10305));
				actions.add(new com.avaya.sce.runtime.Next("GetPrepaidInfo_PC", "(Existing Prepaid Customer)").setDebugId(9401));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition6", "KnowCaller_MN:Value", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "constants:KnowCallerMenu_RetVal_Installation", true).setDebugId(9402)).evaluate(mySession)) {
				actions = new java.util.ArrayList(2);
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("appVariables:tries", "constants:One", false).setDebugId(10306));
				actions.add(new com.avaya.sce.runtime.Next("GetCAFNumber_PC", "(Installation)").setDebugId(9403));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition7", "KnowCaller_MN:Value", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "constants:KnowCallerMenu_RetVal_NewConnection", true).setDebugId(9404)).evaluate(mySession)) {
				actions = new java.util.ArrayList(1);
				actions.add(new com.avaya.sce.runtime.Next("NewConnection_MN", "(New Connection)").setDebugId(9405));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition8", "KnowCaller_MN:Value", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "constants:GPMR_MainMenu", true).setDebugId(12074)).evaluate(mySession)) {
				actions = new java.util.ArrayList(1);
				actions.add(new com.avaya.sce.runtime.Next("Mainmenu_MN", "(Main Menu)").setDebugId(12075));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition9", "KnowCaller_MN:Value", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "constants:GPMR_PreviousMenu", true).setDebugId(12076)).evaluate(mySession)) {
				actions = new java.util.ArrayList(1);
				actions.add(new com.avaya.sce.runtime.Next("Mainmenu_MN", "(Previous Menu)").setDebugId(12077));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			} else {
				actions = new java.util.ArrayList(2);
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("appVariables:transferCode", "TransferCodes:DAKC_TR_0074", false).setDebugId(9408));
				actions.add(new com.avaya.sce.runtime.Next("Check_SRC", "(Complaints)").setDebugId(9407));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;
			}


		} else {
			actions = new java.util.ArrayList(2);
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("appVariables:transferCode", "TransferCodes:DAKC_TR_0073", false).setDebugId(9397));
			actions.add(new com.avaya.sce.runtime.Next("Check_SRC", "(Exceeded Tries)").setDebugId(9393));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;
		}


		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
}
