package flow;

import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;
import com.rcom.bb.model.BANDetails;
import com.rcom.bb.model.ValidatePostpaidBBInfo;
import com.rcom.bb.resource.IVRDBServiceInstance;
import com.rcom.broadband.Constants;
import com.rcom.broadband.StackTrace;
import com.servion.util.IVRDataBean;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2015-MAY-22  08:38:19 PM
 */
public class DB_AccessDSS_BAN extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2015-MAY-22  08:38:19 PM
	 */
	public DB_AccessDSS_BAN() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	@Override
	public void requestBegin(SCESession mySession) {
	
		String DB_Result = Constants.FAILURE;
		String postpaidInput = null;
		String verifiedBy = null;
		IVRDataBean ivrDataBean = null;
		
		String BAN = null;
		String mobilePhone = null;
		String workPhone = null;
		String subscriberId = null;
		
		try
		{
			
			ITraceInfo trace = mySession.getTraceOutput();
			
			/** getting the IVRData bean from session**/
			ivrDataBean = (IVRDataBean) mySession.getProperty(Constants.IVR_DATA_BEAN);
			
			postpaidInput = mySession.getVariableField(IProjectVariables.KNOW_CALLER__PC, IProjectVariables.KNOW_CALLER__PC_FIELD_VALUE).getStringValue();
			trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "Postpaid Info Entered by caller : " +postpaidInput);
			
			ValidatePostpaidBBInfo validatePostpaidBBInfo = new ValidatePostpaidBBInfo();
			validatePostpaidBBInfo.setUserValue(postpaidInput);
			
			validatePostpaidBBInfo = IVRDBServiceInstance.getInstance().validatePostpaidBBInfo(ivrDataBean, validatePostpaidBBInfo);
			
			verifiedBy = validatePostpaidBBInfo.getVerifiedBy();
			trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "Verified By : " +verifiedBy);
			
			if(verifiedBy != null && !Constants.EMPTY.equalsIgnoreCase(verifiedBy))
			{
				
				if(verifiedBy.equalsIgnoreCase(Constants.BAN_VERIFIED))
				{
					mySession.getVariableField(IProjectVariables.APP_VARIABLES, IProjectVariables.APP_VARIABLES_FIELD_IS_BANVERIFIED).setValue(true);
					DB_Result = Constants.SUCCESS;
				}
				else if(verifiedBy.equalsIgnoreCase(Constants.NOT_VERIFIED))
				{
					mySession.getVariableField(IProjectVariables.APP_VARIABLES, IProjectVariables.APP_VARIABLES_FIELD_IS_NOT_VERIFIED).setValue(true);
					DB_Result = Constants.SUCCESS;
				}
				else
				{
					mySession.getVariableField(IProjectVariables.APP_VARIABLES, IProjectVariables.APP_VARIABLES_FIELD_IS_BANVERIFIED).setValue(false);
					mySession.getVariableField(IProjectVariables.APP_VARIABLES, IProjectVariables.APP_VARIABLES_FIELD_IS_NOT_VERIFIED).setValue(false);
					
					trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "Verified By : " +verifiedBy);
					trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "Hence trying to get BAN.");
					
					mySession.getVariableField(IProjectVariables.APP_VARIABLES, IProjectVariables.APP_VARIABLES_FIELD_POTSBIA__INPUT).setValue(postpaidInput);
					
					BANDetails banDetails = new BANDetails();
					
					banDetails.setCli(postpaidInput);
					
					banDetails = IVRDBServiceInstance.getInstance().getBanDetails(ivrDataBean, banDetails);
					BAN = banDetails.getBan();
					mobilePhone = banDetails.getMobilePhone();
					workPhone = banDetails.getWorkPhone();
					subscriberId = banDetails.getSubscriberID();
					trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "BAN : " +BAN);
					trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "Mobile Phone : " +mobilePhone);
					trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "Work Phone : " +workPhone);
					trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "Subscriber ID : " +subscriberId);
					if(BAN != null && !Constants.EMPTY.equalsIgnoreCase(BAN))
					{
						DB_Result = Constants.SUCCESS;
						
						mySession.getVariableField(IProjectVariables.APP_VARIABLES, IProjectVariables.APP_VARIABLES_FIELD_BAN).setValue(BAN);
						mySession.getVariableField(IProjectVariables.APP_VARIABLES, IProjectVariables.APP_VARIABLES_FIELD_CBB__INPUT).setValue(BAN);
						
						mySession.getVariableField(IProjectVariables.APP_VARIABLES, IProjectVariables.APP_VARIABLES_FIELD_MOBILE_NO).setValue(mobilePhone);
						mySession.getVariableField(IProjectVariables.APP_VARIABLES, IProjectVariables.APP_VARIABLES_FIELD_WORK_PHONE).setValue(workPhone);
						mySession.getVariableField(IProjectVariables.APP_VARIABLES, IProjectVariables.APP_VARIABLES_FIELD_SUBSCRIBER_ID).setValue(subscriberId);
						
						
					}
					else
					{
						DB_Result = Constants.FAILURE;
					}
				}
			}
			else
			{
				DB_Result = Constants.FAILURE;
			}
			
			
			mySession.getVariableField(IProjectVariables.APP_VARIABLES, IProjectVariables.APP_VARIABLES_FIELD_DB__RESULT).setValue(DB_Result);
			
		} catch (Exception e)
		{
			StackTrace.PrintException(e);
			mySession.getVariableField(IProjectVariables.APP_VARIABLES, IProjectVariables.APP_VARIABLES_FIELD_DB__RESULT).setValue(Constants.FAILURE);
		}
		
	}
	
	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2016-SEP-28  04:13:57 PM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = null;
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2016-SEP-28  04:13:57 PM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2016-SEP-28  04:13:57 PM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition1", "appVariables:DB_Result", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "constants:success", true).setDebugId(1835)).evaluate(mySession)) {

			if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition2", "appVariables:IsBANVerified", com.avaya.sce.runtime.Expression.IS_TRUE).setDebugId(1837)).evaluate(mySession)) {

				if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition3", "appVariables:IsSouthCircle", com.avaya.sce.runtime.Expression.IS_TRUE).setDebugId(12689)).evaluate(mySession)) {
					actions = new java.util.ArrayList(2);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("appVariables:transferCode", "TransferCodes:DAKC_TR_0003", false).setDebugId(1843));
					actions.add(new com.avaya.sce.runtime.Next("Check_SRC", "(BAN Verified South)").setDebugId(1838));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				} else {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.Next("Check_SRC", "(BAN Verified Other)").setDebugId(12691));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;
				}


			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition4", "appVariables:IsNotVerified", com.avaya.sce.runtime.Expression.IS_TRUE).setDebugId(1839)).evaluate(mySession)) {

				if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition5", "appVariables:tries", com.avaya.sce.runtime.Expression.STRING_EQUAL, "constants:Three", true).setDebugId(1847)).evaluate(mySession)) {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.Next("KnowCallerTriesExceeded_PP", "(Tries Exceeded)").setDebugId(1848));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				} else {
					actions = new java.util.ArrayList(2);
					actions.add(new com.avaya.sce.runtime.varoperations.Increment("appVariables:tries").setDebugId(1846));
					actions.add(new com.avaya.sce.runtime.Next("InvalidEntry_PP", "(Not Verified)").setDebugId(1840));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;
				}


			} else {
				actions = new java.util.ArrayList(2);
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("appVariables:tries", "constants:One", false).setDebugId(8739));
				actions.add(new com.avaya.sce.runtime.Next("SF_HotFlash_AccInfo", "(Any other verified)").setDebugId(1842));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;
			}


		} else {
			actions = new java.util.ArrayList(2);
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("appVariables:transferCode", "TransferCodes:DAKC_TR_0052", false).setDebugId(8738));
			actions.add(new com.avaya.sce.runtime.Next("Linkdown_PP", "(Failure)").setDebugId(1689));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;
		}


		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
}
