/**
 * Last generated by Orchestration Designer at: 2016-JAN-20  12:59:24 PM
 */
package english.prompts;

import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;
import com.rcom.utilities.IVRConstants;

import flow.IProjectVariables;

public class Ann_LangSelection extends com.avaya.sce.runtime.Prompt {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for Ann_LangSelection.
	 */
	public Ann_LangSelection() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}


	/**
	 * This method is generated automatically and should not be manually edited
	 * To manually edit the prompt, override:
	 * void updatePrompt()
	 * Last generated by Orchestration Designer at: 2017-JUL-27  12:38:49 PM
	 */
	public void buildPrompt(){
		com.avaya.sce.runtime.Format format = null;
		com.avaya.sce.runtime.RenderHint hint = null;
		com.avaya.sce.runtime.MediaPage mediaPage = null;
		setBarginType(com.avaya.sce.runtimecommon.SCERT.BARGIN_SPEECH);
		setName("Ann_LangSelection");
		setOrder(com.avaya.sce.runtime.Prompt.STANDARD);

		// Prompt level 1
		setTimeout(1,8000);
		setBargin(1,true);

	}
	@Override
	public void updatePrompt(SCESession mySession) {
		//Auto-generated method stub
		super.updatePrompt(mySession);
		
		String phrasePath = IVRConstants.EMPTY_QUOTES;
		String language = IVRConstants.EMPTY_QUOTES;
		int total_langs = IVRConstants.ZERO;
		String waveFilePath = IVRConstants.EMPTY_QUOTES;
		String waveFileName= IVRConstants.EMPTY_QUOTES;
		String pressOptionWaveFile= IVRConstants.EMPTY_QUOTES;
		String pressOptionODVar= IVRConstants.EMPTY_QUOTES;
		
		ITraceInfo itraceInfo = null; 
		
		try{
			// Loading the trace object
			itraceInfo = mySession.getTraceOutput();
			itraceInfo.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "# Announcing languages menu.");	
			
			phrasePath = mySession.getVariableField(IProjectVariables.VAR__PHRASES, IProjectVariables.VAR__PHRASES_FIELD_STATIC__URL).getStringValue();
			waveFileName = mySession.getVariableField(IProjectVariables.VAR__LANG, IProjectVariables.VAR__LANG_FIELD_WAVFILE__NAME).getStringValue();
			pressOptionODVar = mySession.getVariableField(IProjectVariables.VAR__LANG, IProjectVariables.VAR__LANG_FIELD_PRESS__WAVFILE__NAME).getStringValue();
			total_langs = mySession.getVariableField(IProjectVariables.VAR__LANG, IProjectVariables.VAR__LANG_FIELD_TOTAL__LANG).getIntValue();
			
			itraceInfo.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "# phrasePath:" + phrasePath);
			itraceInfo.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "# Language wave fileName- " +waveFileName);
			itraceInfo.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "# press_wav_filename- " +pressOptionODVar);
			//itraceInfo.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "# number_wav_filename- " +number_wav_filename);
			
			itraceInfo.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "# total languages:" + total_langs);
			
			for(int index = 1; index <= total_langs; index ++){
				pressOptionWaveFile = pressOptionODVar;//This is to prevent appending values for the wave file options.
				//Forming the language menu itesm. Eg: To continue in English..
				language = mySession.getVariableField(IProjectVariables.VAR__LANG, IVRConstants.LANG_ + Integer.toString(index)).getStringValue();
				waveFilePath = phrasePath + language + IVRConstants.SLASH + IVRConstants.STATIC + IVRConstants.SLASH + waveFileName;
				itraceInfo.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "# Announcing wave file path:" + waveFilePath);	
				mySession.getVariableField(IProjectVariables.VAR__LANG, IVRConstants.ANN_LANG_OPTION_ + Integer.toString(index)).setValue(waveFilePath);
				add(1, new com.avaya.sce.runtime.PhraseVariableElement("VAR_LANG:ann_lang_option_" + Integer.toString(index), com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL,false));
				
				//Forming the press 1,  Press 2 etc Options.s
				pressOptionWaveFile += Integer.toString(index).trim() + IVRConstants.EXT_WAVE; //This will form the complete wave file name. Eg: 45000.wav
				waveFilePath = phrasePath + language + IVRConstants.SLASH + IVRConstants.STATIC + IVRConstants.SLASH  + pressOptionWaveFile;
				itraceInfo.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "# Announcing press option file path:" + waveFilePath);
				mySession.getVariableField(IProjectVariables.VAR__LANG, IVRConstants.PRESS_OPTION_ + Integer.toString(index)).setValue(waveFilePath);
				add(1, new com.avaya.sce.runtime.PhraseVariableElement("VAR_LANG:press_" + Integer.toString(index), com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL,false));
			}
			
		}catch(Exception e){;
			
			
		}
	}



}
