/**
 * Last generated by Orchestration Designer at: 2015-NOV-05  12:15:34 AM
 */
package english.prompts;

import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;
import com.hp.utilities.IVRConstants;

import flow.IProjectVariables;

public class Ann_Transfer extends com.avaya.sce.runtime.Prompt {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for Ann_Transfer.
	 */
	public Ann_Transfer() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}


	/**
	 * This method is generated automatically and should not be manually edited
	 * To manually edit the prompt, override:
	 * void updatePrompt()
	 * Last generated by Orchestration Designer at: 2017-JUL-12  01:45:43 PM
	 */
	public void buildPrompt(){
		com.avaya.sce.runtime.Format format = null;
		com.avaya.sce.runtime.RenderHint hint = null;
		com.avaya.sce.runtime.MediaPage mediaPage = null;
		setBarginType(com.avaya.sce.runtimecommon.SCERT.BARGIN_SPEECH);
		setName("Ann_Transfer");
		setOrder(com.avaya.sce.runtime.Prompt.STANDARD);

		// Prompt level 1
		setTimeout(1,8000);
		setBargin(1,true);

	}
	public void updatePrompt(SCESession mySession) {
		//Auto-generated method stub
		super.updatePrompt(mySession);
		
		String phrasePath = IVRConstants.EMPTY_QUOTES;
		String language = IVRConstants.EMPTY_QUOTES;
		int total_langs = IVRConstants.ZERO;
		String waveFilePath = IVRConstants.EMPTY_QUOTES;
		String waveFileName= IVRConstants.EMPTY_QUOTES;
		
		ITraceInfo itraceInfo = null; 
		
		try{
			// Loading the trace object
			itraceInfo = mySession.getTraceOutput();
			
			
			phrasePath = mySession.getVariableField(IProjectVariables.VAR__PHRASES, IProjectVariables.VAR__PHRASES_FIELD_STATIC__URL).getStringValue();
			waveFileName = mySession.getVariableField(IProjectVariables.CALL_INFO, IProjectVariables.CALL_INFO_FIELD_ANN__TRANSFER).getStringValue();
			
			itraceInfo.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "# phrasePath:" + phrasePath);
			itraceInfo.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "# waveFileName:" + waveFileName);
			
		
			 String lang_Code = mySession.getVariableField(IProjectVariables.CALL_INFO, IProjectVariables.CALL_INFO_FIELD_CURRENT_LANGUAGE).getStringValue();
			 itraceInfo.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "# Language:" + lang_Code);
             waveFilePath = phrasePath + lang_Code + IVRConstants.SLASH + IVRConstants.STATIC + IVRConstants.SLASH +waveFileName;
             itraceInfo.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "# Announcing wave file path:" + waveFilePath);	
				mySession.getVariableField(IProjectVariables.TVP__VARS, IProjectVariables.TVP__VARS_FIELD_TRANSFER_MESSAGE).setValue(waveFilePath);
				add(1, new com.avaya.sce.runtime.PhraseVariableElement("TVP_VARs:transferMessage", com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL,false));
				}

			catch(Exception e){
				itraceInfo.writeln(ITraceInfo.TRACE_LEVEL_ERROR, "# Error in Ann_Transfer" + e.getMessage());
				
			}
			
			
		}

}
