package flow;

/**
 * This is a special reserved class that is repsonsible for loading application 
 * variables as well as the forward to the actual first form of the application.<br>
 * This class should not be manually edited as changes may be overridden by the 
 * code generator.<br>
 * Last generated by Orchestration Designer at: 2015-APR-01  07:17:17 PM
 */
public class Start extends com.avaya.sce.runtime.Entry {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2015-APR-01  07:17:17 PM
	 */
	public Start() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * This method is generated automatically.  Any changes may be overwritten.
	 * Returns the submit object that will redirect application flow to the first
	 * form in the application.  This also adds various standard variables to the
	 * list of data to be submitted to the runtime variable table.
	 * Last generated by Orchestration Designer at: 2017-JUN-16  12:43:49 PM
	 * @return the Submit object that contains the standard variables and the first form
	 */
	public com.avaya.sce.runtime.Submit getSubmit(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Submit submit = new com.avaya.sce.runtime.Submit("CallStart");
		return ( submit );
	}
	/**
	 * This method initializes the SCE session with the variables that
	 * are defined in the application.<BR>
	 * 
	 * This method is generated automatically and should not be manually
	 * edited because changes may be overwritten by future code 
	 * generation.
	 * Last generated by Orchestration Designer at: 2017-JUN-16  12:43:49 PM
	 */
	public void initializeVariables(com.avaya.sce.runtimecommon.SCESession session) {
		com.avaya.sce.runtimecommon.IVariable variable = null;
		String[] variableFields = null;

		variable = com.avaya.sce.runtime.SimpleVariable.createSimpleVariable(IProjectVariables.APP__NAME, "", null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.DUMMY_DM_FIELD_ANNOUNCE_ID,
			IProjectVariables.DUMMY_DM_FIELD_CONFIDENCE,
			IProjectVariables.DUMMY_DM_FIELD_CONFIRMATION_REMAINING,
			IProjectVariables.DUMMY_DM_FIELD_DIALOG_NAME,
			IProjectVariables.DUMMY_DM_FIELD_INPUT_TYPE,
			IProjectVariables.DUMMY_DM_FIELD_MENU_END_TIME,
			IProjectVariables.DUMMY_DM_FIELD_MENU_ID,
			IProjectVariables.DUMMY_DM_FIELD_MENU_START_TIME,
			IProjectVariables.DUMMY_DM_FIELD_N_BEST_VALUES,
			IProjectVariables.DUMMY_DM_FIELD_NOINPUT_REMAINING,
			IProjectVariables.DUMMY_DM_FIELD_NOMATCH_REMAINING,
			IProjectVariables.DUMMY_DM_FIELD_OTHER_SLOT,
			IProjectVariables.DUMMY_DM_FIELD_RECORDED__UTTERANCE,
			IProjectVariables.DUMMY_DM_FIELD_RETURN_CODE,
			IProjectVariables.DUMMY_DM_FIELD_SPECIFIC_SLOT,
			IProjectVariables.DUMMY_DM_FIELD_UTTERANCE,
			IProjectVariables.DUMMY_DM_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.DUMMY_DM, variableFields, null, session, false, false );
		session.putVariable(variable);

		variable = com.avaya.sce.runtime.SimpleVariable.createSimpleVariable(IProjectVariables.TRANSFER, "", null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.REDIRECTINFO_FIELD_PRESENTATIONINFO,
			IProjectVariables.REDIRECTINFO_FIELD_REASON,
			IProjectVariables.REDIRECTINFO_FIELD_SCREENINGINFO,
			IProjectVariables.REDIRECTINFO_FIELD_URI };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.REDIRECTINFO, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.APP_VARIABLES_FIELD_CIRCLE,
			IProjectVariables.APP_VARIABLES_FIELD_IS_EXCEPTION,
			IProjectVariables.APP_VARIABLES_FIELD_NETWORK_ERROR,
			IProjectVariables.APP_VARIABLES_FIELD_REASON_CODE,
			IProjectVariables.APP_VARIABLES_FIELD_TRANSFER_CODE,
			IProjectVariables.APP_VARIABLES_FIELD_TRANSFER_VDN,
			IProjectVariables.APP_VARIABLES_FIELD_TRIES_COUNT,
			IProjectVariables.APP_VARIABLES_FIELD_UUI_DATA };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.APP_VARIABLES, variableFields, new String[] {"", "", "", "", "", "", "0", ""}, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.GET_PINNUMBER__MN___0_0_0_1_FIELD_ANNOUNCE_ID,
			IProjectVariables.GET_PINNUMBER__MN___0_0_0_1_FIELD_CONFIDENCE,
			IProjectVariables.GET_PINNUMBER__MN___0_0_0_1_FIELD_CONFIRMATION_REMAINING,
			IProjectVariables.GET_PINNUMBER__MN___0_0_0_1_FIELD_DIALOG_NAME,
			IProjectVariables.GET_PINNUMBER__MN___0_0_0_1_FIELD_INPUT_TYPE,
			IProjectVariables.GET_PINNUMBER__MN___0_0_0_1_FIELD_MENU_END_TIME,
			IProjectVariables.GET_PINNUMBER__MN___0_0_0_1_FIELD_MENU_ID,
			IProjectVariables.GET_PINNUMBER__MN___0_0_0_1_FIELD_MENU_START_TIME,
			IProjectVariables.GET_PINNUMBER__MN___0_0_0_1_FIELD_N_BEST_VALUES,
			IProjectVariables.GET_PINNUMBER__MN___0_0_0_1_FIELD_NOINPUT_REMAINING,
			IProjectVariables.GET_PINNUMBER__MN___0_0_0_1_FIELD_NOMATCH_REMAINING,
			IProjectVariables.GET_PINNUMBER__MN___0_0_0_1_FIELD_OTHER_SLOT,
			IProjectVariables.GET_PINNUMBER__MN___0_0_0_1_FIELD_RECORDED__UTTERANCE,
			IProjectVariables.GET_PINNUMBER__MN___0_0_0_1_FIELD_RETURN_CODE,
			IProjectVariables.GET_PINNUMBER__MN___0_0_0_1_FIELD_SPECIFIC_SLOT,
			IProjectVariables.GET_PINNUMBER__MN___0_0_0_1_FIELD_UTTERANCE,
			IProjectVariables.GET_PINNUMBER__MN___0_0_0_1_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.GET_PINNUMBER__MN___0_0_0_1, variableFields, null, session, false, false );
		variable.getComplexVariable().getField(IProjectVariables.GET_PINNUMBER__MN___0_0_0_1_FIELD_RECORDED__UTTERANCE).setAttribute(com.avaya.sce.runtimecommon.IVariableField.VARATTR_PRIVATE, true);
		variable.getComplexVariable().getField(IProjectVariables.GET_PINNUMBER__MN___0_0_0_1_FIELD_UTTERANCE).setAttribute(com.avaya.sce.runtimecommon.IVariableField.VARATTR_PRIVATE, true);
		variable.getComplexVariable().getField(IProjectVariables.GET_PINNUMBER__MN___0_0_0_1_FIELD_VALUE).setAttribute(com.avaya.sce.runtimecommon.IVariableField.VARATTR_PRIVATE, true);
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.DATE_FIELD_AUDIO,
			IProjectVariables.DATE_FIELD_DAYOFMONTH,
			IProjectVariables.DATE_FIELD_DAYOFWEEK,
			IProjectVariables.DATE_FIELD_DAYOFWEEKNUM,
			IProjectVariables.DATE_FIELD_DAYOFYEAR,
			IProjectVariables.DATE_FIELD_MONTH,
			IProjectVariables.DATE_FIELD_MONTHINYEAR,
			IProjectVariables.DATE_FIELD_YEAR };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.DATE, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.DM_INPUT_PARAMETER_FIELD_GLOBAL_PROPERTY_FILE_NAME,
			IProjectVariables.DM_INPUT_PARAMETER_FIELD_INITIAL_PROMPT,
			IProjectVariables.DM_INPUT_PARAMETER_FIELD_PROPERTY_FILE_LOCATION,
			IProjectVariables.DM_INPUT_PARAMETER_FIELD_PROPERTY_FILE_NAME };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.DM_INPUT_PARAMETER, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.CONSTANT_FIELD_SUCCESS,
			IProjectVariables.CONSTANT_FIELD_THREE,
			IProjectVariables.CONSTANT_FIELD_YES };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.CONSTANT, variableFields, new String[] {"success", "3", "yes"}, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.THANK_YOU__PA_FIELD_ANNOUNCE_ID,
			IProjectVariables.THANK_YOU__PA_FIELD_CONFIDENCE,
			IProjectVariables.THANK_YOU__PA_FIELD_CONFIRMATION_REMAINING,
			IProjectVariables.THANK_YOU__PA_FIELD_DIALOG_NAME,
			IProjectVariables.THANK_YOU__PA_FIELD_INPUT_TYPE,
			IProjectVariables.THANK_YOU__PA_FIELD_MENU_END_TIME,
			IProjectVariables.THANK_YOU__PA_FIELD_MENU_ID,
			IProjectVariables.THANK_YOU__PA_FIELD_MENU_START_TIME,
			IProjectVariables.THANK_YOU__PA_FIELD_N_BEST_VALUES,
			IProjectVariables.THANK_YOU__PA_FIELD_NOINPUT_REMAINING,
			IProjectVariables.THANK_YOU__PA_FIELD_NOMATCH_REMAINING,
			IProjectVariables.THANK_YOU__PA_FIELD_OTHER_SLOT,
			IProjectVariables.THANK_YOU__PA_FIELD_RECORDED__UTTERANCE,
			IProjectVariables.THANK_YOU__PA_FIELD_RETURN_CODE,
			IProjectVariables.THANK_YOU__PA_FIELD_SPECIFIC_SLOT,
			IProjectVariables.THANK_YOU__PA_FIELD_UTTERANCE,
			IProjectVariables.THANK_YOU__PA_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.THANK_YOU__PA, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.PROPERTY_FILE_NAME_FIELD_GET_PINNUMBER,
			IProjectVariables.PROPERTY_FILE_NAME_FIELD_GLOBAL,
			IProjectVariables.PROPERTY_FILE_NAME_FIELD_LINK_DOWN_ANNC,
			IProjectVariables.PROPERTY_FILE_NAME_FIELD_NOT_AUTHORIZED_ANNC,
			IProjectVariables.PROPERTY_FILE_NAME_FIELD_THANK_YOU_ANNC,
			IProjectVariables.PROPERTY_FILE_NAME_FIELD_WELCOME_ANNC };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.PROPERTY_FILE_NAME, variableFields, new String[] {"GetPINNumber.properties", "global.properties", "LinkDownAnnc.properties", "NotAuthorizedAnnc.properties", "ThankYouAnnc.properties", "WelcomeAnnc.properties"}, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.NOT_AUTHORIZED_ANNC__PA___0_0_0_2_FIELD_ANNOUNCE_ID,
			IProjectVariables.NOT_AUTHORIZED_ANNC__PA___0_0_0_2_FIELD_CONFIDENCE,
			IProjectVariables.NOT_AUTHORIZED_ANNC__PA___0_0_0_2_FIELD_CONFIRMATION_REMAINING,
			IProjectVariables.NOT_AUTHORIZED_ANNC__PA___0_0_0_2_FIELD_DIALOG_NAME,
			IProjectVariables.NOT_AUTHORIZED_ANNC__PA___0_0_0_2_FIELD_INPUT_TYPE,
			IProjectVariables.NOT_AUTHORIZED_ANNC__PA___0_0_0_2_FIELD_MENU_END_TIME,
			IProjectVariables.NOT_AUTHORIZED_ANNC__PA___0_0_0_2_FIELD_MENU_ID,
			IProjectVariables.NOT_AUTHORIZED_ANNC__PA___0_0_0_2_FIELD_MENU_START_TIME,
			IProjectVariables.NOT_AUTHORIZED_ANNC__PA___0_0_0_2_FIELD_N_BEST_VALUES,
			IProjectVariables.NOT_AUTHORIZED_ANNC__PA___0_0_0_2_FIELD_NOINPUT_REMAINING,
			IProjectVariables.NOT_AUTHORIZED_ANNC__PA___0_0_0_2_FIELD_NOMATCH_REMAINING,
			IProjectVariables.NOT_AUTHORIZED_ANNC__PA___0_0_0_2_FIELD_OTHER_SLOT,
			IProjectVariables.NOT_AUTHORIZED_ANNC__PA___0_0_0_2_FIELD_RECORDED__UTTERANCE,
			IProjectVariables.NOT_AUTHORIZED_ANNC__PA___0_0_0_2_FIELD_RETURN_CODE,
			IProjectVariables.NOT_AUTHORIZED_ANNC__PA___0_0_0_2_FIELD_SPECIFIC_SLOT,
			IProjectVariables.NOT_AUTHORIZED_ANNC__PA___0_0_0_2_FIELD_UTTERANCE,
			IProjectVariables.NOT_AUTHORIZED_ANNC__PA___0_0_0_2_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.NOT_AUTHORIZED_ANNC__PA___0_0_0_2, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.LINK_DOWN__PA___0_0_1_2_FIELD_ANNOUNCE_ID,
			IProjectVariables.LINK_DOWN__PA___0_0_1_2_FIELD_CONFIDENCE,
			IProjectVariables.LINK_DOWN__PA___0_0_1_2_FIELD_CONFIRMATION_REMAINING,
			IProjectVariables.LINK_DOWN__PA___0_0_1_2_FIELD_DIALOG_NAME,
			IProjectVariables.LINK_DOWN__PA___0_0_1_2_FIELD_INPUT_TYPE,
			IProjectVariables.LINK_DOWN__PA___0_0_1_2_FIELD_MENU_END_TIME,
			IProjectVariables.LINK_DOWN__PA___0_0_1_2_FIELD_MENU_ID,
			IProjectVariables.LINK_DOWN__PA___0_0_1_2_FIELD_MENU_START_TIME,
			IProjectVariables.LINK_DOWN__PA___0_0_1_2_FIELD_N_BEST_VALUES,
			IProjectVariables.LINK_DOWN__PA___0_0_1_2_FIELD_NOINPUT_REMAINING,
			IProjectVariables.LINK_DOWN__PA___0_0_1_2_FIELD_NOMATCH_REMAINING,
			IProjectVariables.LINK_DOWN__PA___0_0_1_2_FIELD_OTHER_SLOT,
			IProjectVariables.LINK_DOWN__PA___0_0_1_2_FIELD_RECORDED__UTTERANCE,
			IProjectVariables.LINK_DOWN__PA___0_0_1_2_FIELD_RETURN_CODE,
			IProjectVariables.LINK_DOWN__PA___0_0_1_2_FIELD_SPECIFIC_SLOT,
			IProjectVariables.LINK_DOWN__PA___0_0_1_2_FIELD_UTTERANCE,
			IProjectVariables.LINK_DOWN__PA___0_0_1_2_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.LINK_DOWN__PA___0_0_1_2, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.WELCOME_ANNC__PA___0_0_0_1_FIELD_ANNOUNCE_ID,
			IProjectVariables.WELCOME_ANNC__PA___0_0_0_1_FIELD_CONFIDENCE,
			IProjectVariables.WELCOME_ANNC__PA___0_0_0_1_FIELD_CONFIRMATION_REMAINING,
			IProjectVariables.WELCOME_ANNC__PA___0_0_0_1_FIELD_DIALOG_NAME,
			IProjectVariables.WELCOME_ANNC__PA___0_0_0_1_FIELD_INPUT_TYPE,
			IProjectVariables.WELCOME_ANNC__PA___0_0_0_1_FIELD_MENU_END_TIME,
			IProjectVariables.WELCOME_ANNC__PA___0_0_0_1_FIELD_MENU_ID,
			IProjectVariables.WELCOME_ANNC__PA___0_0_0_1_FIELD_MENU_START_TIME,
			IProjectVariables.WELCOME_ANNC__PA___0_0_0_1_FIELD_N_BEST_VALUES,
			IProjectVariables.WELCOME_ANNC__PA___0_0_0_1_FIELD_NOINPUT_REMAINING,
			IProjectVariables.WELCOME_ANNC__PA___0_0_0_1_FIELD_NOMATCH_REMAINING,
			IProjectVariables.WELCOME_ANNC__PA___0_0_0_1_FIELD_OTHER_SLOT,
			IProjectVariables.WELCOME_ANNC__PA___0_0_0_1_FIELD_RECORDED__UTTERANCE,
			IProjectVariables.WELCOME_ANNC__PA___0_0_0_1_FIELD_RETURN_CODE,
			IProjectVariables.WELCOME_ANNC__PA___0_0_0_1_FIELD_SPECIFIC_SLOT,
			IProjectVariables.WELCOME_ANNC__PA___0_0_0_1_FIELD_UTTERANCE,
			IProjectVariables.WELCOME_ANNC__PA___0_0_0_1_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.WELCOME_ANNC__PA___0_0_0_1, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.DMPROPERTY_FIELD_ASS__CONFIG_FILE_PATH,
			IProjectVariables.DMPROPERTY_FIELD_BEN__CONFIG_FILE_PATH,
			IProjectVariables.DMPROPERTY_FIELD_COLLECT_DATA_CARD__TELV__MN___0_0_0_2,
			IProjectVariables.DMPROPERTY_FIELD_COLLECT_MOBILE_NUMBER__TELV__MN___0_0_0_4,
			IProjectVariables.DMPROPERTY_FIELD_CONFIG_FILE_PATH,
			IProjectVariables.DMPROPERTY_FIELD_CONFIRM_DATA_CARD__TELV__MN___0_0_0_3,
			IProjectVariables.DMPROPERTY_FIELD_CONFIRM_MOBILE_NUMBER__TELV__MN___0_0_0_5,
			IProjectVariables.DMPROPERTY_FIELD_DUMMY,
			IProjectVariables.DMPROPERTY_FIELD_ENG__CONFIG_FILE_PATH,
			IProjectVariables.DMPROPERTY_FIELD_GLOBAL,
			IProjectVariables.DMPROPERTY_FIELD_GUJ__CONFIG_FILE_PATH,
			IProjectVariables.DMPROPERTY_FIELD_HIN__CONFIG_FILE_PATH,
			IProjectVariables.DMPROPERTY_FIELD_INITIAL_PROMPT,
			IProjectVariables.DMPROPERTY_FIELD_INVALID_NUMBER__TELV__PA___0_0_0_6,
			IProjectVariables.DMPROPERTY_FIELD_KAN__CONFIG_FILE_PATH,
			IProjectVariables.DMPROPERTY_FIELD_LANGUAGE__TELV__MN___0_0_0_6,
			IProjectVariables.DMPROPERTY_FIELD_LINK_DOWN__TELV__PA___0_0_1_5,
			IProjectVariables.DMPROPERTY_FIELD_MAIN_MENU__TELV__MN___0_0_0_1,
			IProjectVariables.DMPROPERTY_FIELD_MAL__CONFIG_FILE_PATH,
			IProjectVariables.DMPROPERTY_FIELD_MAR__CONFIG_FILE_PATH,
			IProjectVariables.DMPROPERTY_FIELD_MENU_OPTION,
			IProjectVariables.DMPROPERTY_FIELD_MENU_OPTION_COUNT,
			IProjectVariables.DMPROPERTY_FIELD_ORI__CONFIG_FILE_PATH,
			IProjectVariables.DMPROPERTY_FIELD_PUN__CONFIG_FILE_PATH,
			IProjectVariables.DMPROPERTY_FIELD_TAM__CONFIG_FILE_PATH,
			IProjectVariables.DMPROPERTY_FIELD_TEL__CONFIG_FILE_PATH,
			IProjectVariables.DMPROPERTY_FIELD_THANKYOU__TELV__PA___0_0_0_7,
			IProjectVariables.DMPROPERTY_FIELD_TRANSFER__TELV__PA___0_0_0_8__TELV__PA___0_0_1_0,
			IProjectVariables.DMPROPERTY_FIELD_TRIES_EXCEEDED__TELV__PA___0_0_0_2,
			IProjectVariables.DMPROPERTY_FIELD_WELCOME__TELV__PA___0_0_0_1 };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.DMPROPERTY, variableFields, new String[] {"", "", "CollectDataCard_TELV_MN_0002.properties", "CollectMobileNumber_TELV_MN_0004.properties", "", "ConfirmDataCard_TELV_MN_0003.properties", "ConfirmMobileNumber_TELV_MN_0005.properties", "Dummy.properties", "", "global.properties", "", "", "", "InvalidNumber_TELV_PA_0006.properties", "", "Language_TELV_MN_0006.properties", "LinkDown_TELV_PA_0015.properties", "MainMenu_TELV_MN_0001.properties", "", "", "", "", "", "", "", "", "Thankyou_TELV_PA_0007.properties", "Transfer_TELV_PA_0008_TELV_PA_0010.properties", "TriesExceeded_TELV_PA_0002.properties", "Welcome_TELV_PA_0001.properties"}, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.SESSION_FIELD_AAI,
			IProjectVariables.SESSION_FIELD_ANI,
			IProjectVariables.SESSION_FIELD_CALLTAG,
			IProjectVariables.SESSION_FIELD_CHANNEL,
			IProjectVariables.SESSION_FIELD_CHANNELTYPE,
			IProjectVariables.SESSION_FIELD_CONVERSEFIRST,
			IProjectVariables.SESSION_FIELD_CONVERSESECOND,
			IProjectVariables.SESSION_FIELD_CURRENTLANGUAGE,
			IProjectVariables.SESSION_FIELD_DNIS,
			IProjectVariables.SESSION_FIELD_EXIT_CUSTOMER_ID,
			IProjectVariables.SESSION_FIELD_EXIT_INFO_1,
			IProjectVariables.SESSION_FIELD_EXIT_INFO_2,
			IProjectVariables.SESSION_FIELD_EXIT_PREFERRED_PATH,
			IProjectVariables.SESSION_FIELD_EXIT_REASON,
			IProjectVariables.SESSION_FIELD_EXIT_TOPIC,
			IProjectVariables.SESSION_FIELD_LASTERROR,
			IProjectVariables.SESSION_FIELD_MEDIATYPE,
			IProjectVariables.SESSION_FIELD_PROTOCOLNAME,
			IProjectVariables.SESSION_FIELD_PROTOCOLVERSION,
			IProjectVariables.SESSION_FIELD_SESSIONID,
			IProjectVariables.SESSION_FIELD_SESSIONLABEL,
			IProjectVariables.SESSION_FIELD_SHAREDMODE,
			IProjectVariables.SESSION_FIELD_UCID,
			IProjectVariables.SESSION_FIELD_UUI,
			IProjectVariables.SESSION_FIELD_VIDEOBITRATE,
			IProjectVariables.SESSION_FIELD_VIDEOCODEC,
			IProjectVariables.SESSION_FIELD_VIDEOENABLED,
			IProjectVariables.SESSION_FIELD_VIDEOFARFMTP,
			IProjectVariables.SESSION_FIELD_VIDEOFORMAT,
			IProjectVariables.SESSION_FIELD_VIDEOFPS,
			IProjectVariables.SESSION_FIELD_VIDEOHEIGHT,
			IProjectVariables.SESSION_FIELD_VIDEONEARFMTP,
			IProjectVariables.SESSION_FIELD_VIDEOWIDTH,
			IProjectVariables.SESSION_FIELD_VPCALLEDEXTENSION,
			IProjectVariables.SESSION_FIELD_VPCONVERSEONDATA,
			IProjectVariables.SESSION_FIELD_VPCOVERAGEREASON,
			IProjectVariables.SESSION_FIELD_VPCOVERAGETYPE,
			IProjectVariables.SESSION_FIELD_VPRDNIS,
			IProjectVariables.SESSION_FIELD_VPREPORTURL };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.SESSION, variableFields, null, session, false, true );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.TRANSFER_CODES_FIELD_WDVPN__TR___0_0_0_1,
			IProjectVariables.TRANSFER_CODES_FIELD_WDVPN__TR___0_0_0_2,
			IProjectVariables.TRANSFER_CODES_FIELD_WDVPN__TR___0_0_0_3 };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.TRANSFER_CODES, variableFields, new String[] {"WDVPN_TR_0001", "WDVPN_TR_0002", "WDVPN_TR_0003"}, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.VALIDATE_PIN_FIELD_FLAG,
			IProjectVariables.VALIDATE_PIN_FIELD_GET_PINNUMBER };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.VALIDATE_PIN, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.DD_LAST_EXCEPTION_FIELD_ERRORCODE,
			IProjectVariables.DD_LAST_EXCEPTION_FIELD_MESSAGE,
			IProjectVariables.DD_LAST_EXCEPTION_FIELD_OBJECT,
			IProjectVariables.DD_LAST_EXCEPTION_FIELD_STACKTRACE,
			IProjectVariables.DD_LAST_EXCEPTION_FIELD_TYPE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.DD_LAST_EXCEPTION, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.TIME_FIELD_AUDIO,
			IProjectVariables.TIME_FIELD_HOUR,
			IProjectVariables.TIME_FIELD_MILLISECOND,
			IProjectVariables.TIME_FIELD_MINUTE,
			IProjectVariables.TIME_FIELD_SECOND,
			IProjectVariables.TIME_FIELD_TIMEZONE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.TIME, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.SHAREDUUI_FIELD_ID,
			IProjectVariables.SHAREDUUI_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.SHAREDUUI, variableFields, null, session, false, false );
		session.putVariable(variable);
	}
	/**
	 * This method returns the name of the application.
	 * Last generated by Orchestration Designer at: 2017-JUN-16  12:43:49 PM
	 */
	public String getEntryName() {
		return("RCOM_CF_WDVPN_IVR");
	}
	/**
	 * This method returns a list of life cycle classes for Pluggable Connectors.
	 * Last generated by Orchestration Designer at: 2017-JUN-16  12:43:49 PM
	 */
	public java.util.Collection getPluggableLifeCycle() {
		java.util.ArrayList result = new java.util.ArrayList();
		return(result);
	}
	/**
	 * This method returns a list of VXML contributor classes for Pluggable Connectors.
	 * Last generated by Orchestration Designer at: 2017-JUN-16  12:43:49 PM
	 */
	public java.util.Collection getPluggableVXMLContrib() {
		java.util.ArrayList result = new java.util.ArrayList();
		return(result);
	}
	/**
	 * This method returns the root document for the application.
	 * This method is generated automatically and should not be modified
	 * because changes may be overwritten by future code generation.
	 * Last generated by Orchestration Designer at: 2017-JUN-16  12:43:49 PM
	 */
	public String getRootDoc() {
		return("AppRoot");
	}
	/**
	 * Builds the list of input parameters that are defined for this application 
	 * entry.  This list is built automatically by adding Input Parameter
	 * nodes to AppRoot in the call flow editor.<BR>
	 *
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.
	 *
	 * @return a Collection of <code>java.lang.String</code> objects that
	 * are the names of parameters the application is expecting.
	 * If the AppRoot node does not have any input parameters, then 
	 * this returns an empty list
	 * Last generated by Orchestration Designer at: 2017-JUN-16  12:43:49 PM
	 */
	public java.util.Collection getInputParams(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		list = new java.util.ArrayList();

		return list;
	}
	/**
	 * Builds the list of capture expression that are defined for this application 
	 * entry.  This list is built automatically by adding Capture Expression
	 * items to AppRoot in the call flow editor.<BR>
	 *
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.
	 *
	 * @return a Collection of <code>CaptureExpression</code> objects that
	 * specify the ECMA script expression and the Orchestration Designer 
	 * session variable that will store the captured result.
	 * If the AppRoot node does not have any capture expression items, then 
	 * this returns an empty list
	 * Last generated by Orchestration Designer at: 2017-JUN-16  12:43:49 PM
	 */
	public java.util.Collection getCaptureExpressions(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		list = new java.util.ArrayList();

		return list;
	}
}
