package flow.subflow.Prepaid_Start;

import java.util.ArrayList;

import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;
import com.servion.triplefive.utils.AppConstant;
import com.servion.triplefive.utils.Constants;
import com.servion.triplefive.utils.DynamicMenu;
import com.servion.triplefive.utils.PrintStackTrace;
import com.servion.util.AppProperties;

import flow.IProjectVariables;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2015-MAR-15  10:25:20 PM
 */
public class Get_TopUpSelectAmt extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2015-MAR-15  10:25:20 PM
	 */
	public Get_TopUpSelectAmt() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2015-OCT-27  02:07:54 PM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = new com.avaya.sce.runtime.Next("Prepaid_Start-TopUpSelectAmt");
		next.setDebugId(10171);
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2015-OCT-27  02:07:54 PM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2015-OCT-27  02:07:54 PM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
	
	@Override
	public void requestBegin(SCESession mySession) {
		
		ITraceInfo trace = mySession.getTraceOutput();
		String key = AppConstant.EMPTY_STRING,appName = AppConstant.EMPTY_STRING;
		String minAmount =AppConstant.EMPTY_STRING;
		String minTalkTimet =AppConstant.EMPTY_STRING;
		String maxAmount =AppConstant.EMPTY_STRING;
		String maxTalkTime =AppConstant.EMPTY_STRING;
		ArrayList<String> dynamicValue = null;
		String initialPrompt = AppConstant.EMPTY_STRING;
		String menuOption = AppConstant.EMPTY_STRING;
		int count = 0;
		
		//initial prompt processing...
		try
		{
			appName = mySession.getVariableField(IProjectVariables.APP_NAME).getStringValue();
			minAmount = mySession.getVariableField(IProjectVariables.PREPAID__TOP_UP_DETAIL,IProjectVariables.PREPAID__TOP_UP_DETAIL_FIELD_MIN_AMOUNT).getStringValue();
			maxAmount = mySession.getVariableField(IProjectVariables.PREPAID__TOP_UP_DETAIL,IProjectVariables.PREPAID__TOP_UP_DETAIL_FIELD_MAX_AMOUNT).getStringValue();
			
			trace.writeln(ITraceInfo.TRACE_LEVEL_INFO, "Application Name :: "+appName);
			trace.writeln(ITraceInfo.TRACE_LEVEL_INFO, "Top Up minAmount :: "+minAmount);
			trace.writeln(ITraceInfo.TRACE_LEVEL_INFO, "Top Up maxAmount :: "+maxAmount);
			
			key = appName +AppConstant.SEPERATOR_HYPEN+ AppConstant.MN_0019;
			trace.writeln(ITraceInfo.TRACE_LEVEL_INFO, "Key :: "+key);
			initialPrompt = AppProperties.GetInstance(Constants.AUDIO_CONFIG).getIVRProp(key);
			dynamicValue = new ArrayList<String>();
			
			trace.writeln(ITraceInfo.TRACE_LEVEL_INFO, "Top Up Confirmation initial Prompt Before Dynamic Insertion:: "+initialPrompt);
			if(minAmount != null && !AppConstant.EMPTY_STRING.equals(minAmount)){
				trace.writeln(ITraceInfo.TRACE_LEVEL_INFO, "MAX topup Value is added");
				dynamicValue.add(minAmount+AppConstant.currency);
				menuOption = minAmount + AppConstant.SEPERATOR_COMMA;
				count ++;
			}
			
			if(maxAmount != null && !AppConstant.EMPTY_STRING.equals(maxAmount)){
				trace.writeln(ITraceInfo.TRACE_LEVEL_INFO, "MAX topup Value is added");
				dynamicValue.add(maxAmount+AppConstant.currency);
				menuOption = menuOption+maxAmount;
				count ++;
			}
			
			trace.writeln(ITraceInfo.TRACE_LEVEL_INFO, "dynamicValue :"+dynamicValue);
			
			DynamicMenu objDynamicMenu = new DynamicMenu();
			initialPrompt=objDynamicMenu.playPrompt(dynamicValue, initialPrompt, String.valueOf(count), trace);
			
			trace.writeln(ITraceInfo.TRACE_LEVEL_INFO, "Top Up Confirmation initial Prompt :: "+initialPrompt);
			trace.writeln(ITraceInfo.TRACE_LEVEL_INFO, "Top Up Confirmation initial count :: "+count);
			trace.writeln(ITraceInfo.TRACE_LEVEL_INFO, "Top Up Confirmation initial menuOption :: "+menuOption);
			
			mySession.getVariableField(IProjectVariables.PREPAID__DM_INPUT_PARAMETER, IProjectVariables.PREPAID__DM_INPUT_PARAMETER_FIELD_INITIAL_PROMPT).setValue(initialPrompt);
			mySession.getVariableField(IProjectVariables.PREPAID__DM_INPUT_PARAMETER, IProjectVariables.PREPAID__DM_INPUT_PARAMETER_FIELD_MORE_OPTION_COUNT).setValue(count);
			mySession.getVariableField(IProjectVariables.PREPAID__DM_INPUT_PARAMETER, IProjectVariables.PREPAID__DM_INPUT_PARAMETER_FIELD_MENU_OPTION).setValue(menuOption);
		}
		catch(Exception e)
		{
			PrintStackTrace.PrintException(e);
			trace.writeln(ITraceInfo.TRACE_LEVEL_ERROR, "Exception in Top Up Confirmation initial prompt :: "+e);
		}
		finally
		{
				initialPrompt = null;
		}
	
	}
}
