package flow.subflow.CF_Transfer;

import java.util.List;

import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;
import com.rcom.utilities.IVRConstants;
import com.rcom.utilities.IVRProperties;
import com.rcom.utilities.StackTrace;
import com.rcom.otherflows.model.TransferVDNInfo;
import com.rcom.otherflows.resource.IVRDBServiceInstance;
import com.servion.prepaid.report.GetReportObject;
import com.servion.prepaid.report.IVRREPORTDATA;
import com.servion.prepaid.report.IVRREPORTDATA.CALLINFO;
import com.servion.prepaid.report.IVRREPORTDATA.MENUDETAILS.MENU;
import com.servion.util.IVRDataBean;

import flow.IProjectVariables;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2016-JAN-20  03:39:39 PM
 */
public class Dat_GetTransferVDN extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	


	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2016-JAN-20  03:39:39 PM
	 */
	public Dat_GetTransferVDN() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2017-JUL-27  12:38:48 PM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = new com.avaya.sce.runtime.Next("CF_Transfer-blindTransfer", "Default");
		next.setDebugId(17);
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2017-JUL-27  12:38:48 PM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2016-JAN-20  03:39:39 PM
	 */
	
	public void requestBegin(SCESession mySession) {
		super.requestBegin(mySession);
		
		///String strDataCardFlag = null;
		String strReasonCode		= 		IVRConstants.EMPTY_QUOTES;
		String strTransferVDN 		= 		IVRConstants.EMPTY_QUOTES;
		String strInitialAudios		= 		IVRConstants.EMPTY_QUOTES;
		TransferVDNInfo transferVDNInfo =  new TransferVDNInfo();;
		IVRDataBean ivrDataBean 		=  null;
		GetReportObject getReportObject =  null;
		IVRREPORTDATA ivrreportdata     =  null;
		String propLocation 			=  null;
		IVRProperties ivrProp		    = null;
		CALLINFO callInfo			    = null;
		ITraceInfo traceinfo		    = null;
		String last5Menu			    = IVRConstants.EMPTY_QUOTES;
		ITraceInfo trace			    = null;
		String strUUI 				    = IVRConstants.EMPTY_QUOTES;
		String menuID 					= IVRConstants.EMPTY_QUOTES;
		String strANI					= IVRConstants.EMPTY_QUOTES;
		String strDNIS					= IVRConstants.EMPTY_QUOTES;
		String verifyMDN 				= IVRConstants.EMPTY_QUOTES;
		String language					= IVRConstants.EMPTY_QUOTES;
		String transferAnnwav			= IVRConstants.EMPTY_QUOTES;
		String strCircle				= IVRConstants.EMPTY_QUOTES;
		String strLanguage				= IVRConstants.EMPTY_QUOTES;
		
		try
		{
			/**Assigning the trace object**/
			traceinfo = mySession.getTraceOutput();
			traceinfo.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "Transfer Reson Code:"+mySession.getVariableField(IProjectVariables.CALL_DATA, IProjectVariables.CALL_DATA_FIELD_TRANSFER_REASON_CODE).getStringValue());
			/** getting the IVRData bean from session**/
			ivrDataBean =  (IVRDataBean) mySession.getProperty(IVRConstants.IVRDATABEAN);
		
			/** getting the config path from session**/
			propLocation=mySession.getVariableField(IProjectVariables.VAR__CONFIG,IProjectVariables.VAR__CONFIG_FIELD_CONFIG_FILE_PATH).getStringValue();
			
			traceinfo.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "Started Initiliazation.");
			ivrProp=IVRProperties.getInstance(propLocation, mySession);
			
			/**Deciding the transfer flow**/
			strReasonCode = mySession.getVariableField(IProjectVariables.CALL_DATA, IProjectVariables.CALL_DATA_FIELD_TRANSFER_REASON_CODE).getStringValue();
			traceinfo.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "strReasonCode-" + strReasonCode);
			getReportObject = ivrDataBean.getGetReportObject();
			ivrreportdata = getReportObject.getIvrreportdata();
			callInfo = ivrreportdata.getCALLINFO();
			traceinfo = mySession.getTraceOutput();
			
			traceinfo.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "Menu:"+ivrreportdata.getMENUDETAILS().getMENU());
			List<MENU> menuList = ivrreportdata.getMENUDETAILS().getMENU();
			
			if(menuList  !=null){
				
				for (int i = menuList.size(); (i> (menuList.size()-5)) && (i!=0); i-- ){
					menuID = menuList.get((i-1)).getMENUID();
					traceinfo.writeln(ITraceInfo.TRACE_LEVEL_INFO, "menu ID :"+menuID);
					last5Menu = last5Menu + menuID+"|";
				}
				traceinfo.writeln(ITraceInfo.TRACE_LEVEL_INFO, "Last 5 menu accessed :"+last5Menu);
			}else{
				traceinfo.writeln(ITraceInfo.TRACE_LEVEL_INFO, "No Menu accessed");
			}
			traceinfo.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "Setting the data");
			strANI 		= mySession.getVariableField(IProjectVariables.SESSION, IProjectVariables.SESSION_FIELD_ANI).getStringValue();
			strDNIS 	= mySession.getVariableField(IProjectVariables.SESSION, IProjectVariables.SESSION_FIELD_DNIS).getStringValue();
			language	= mySession.getVariableField(IProjectVariables.CALL_DATA, IProjectVariables.CALL_DATA_FIELD_CURRENT_LANG).getStringValue();
			strUUI = strANI+"|"+strDNIS+"|"+language+"|"+last5Menu+"|"+strReasonCode;
			mySession.getVariableField(IProjectVariables.CALL_DATA, IProjectVariables.CALL_DATA_FIELD_UUIDATA).setValue(strUUI);
			
			traceinfo.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "UUI data:" + strUUI);
			
			transferVDNInfo.setAppName(mySession.getVariableField(IProjectVariables.APP_NAME).getStringValue());
			transferVDNInfo.setCircle(mySession.getVariableField(IProjectVariables.CALL_DATA, IProjectVariables.CALL_DATA_FIELD_CIRCLE).getStringValue());
			transferVDNInfo.setCallType("4");
			transferVDNInfo.setCustomerSegment("3");
			transferVDNInfo.setLanguage(language);
			transferVDNInfo.setTransferReasonCode(strReasonCode);
			/*Testing */
			transferVDNInfo = IVRDBServiceInstance.getIVRDBInstance().getTransferVDN(ivrDataBean, transferVDNInfo);
			
			callInfo.setHOWCALLENDED("TRANSFER");
			if(transferVDNInfo.getTransferVDN1()!=null){
				callInfo.setAGENTEXTN(transferVDNInfo.getTransferVDN1());
				callInfo.setAGENTID(transferVDNInfo.getTransferVDN1());
				callInfo.setTRANSFERVDN(transferVDNInfo.getTransferVDN1());
			}else{
				
			}
			if(transferVDNInfo.getSkillName()!=null)
				callInfo.setSKILLNAME(transferVDNInfo.getSkillName());
			
			callInfo.setUUIDATA(strUUI);
			callInfo.setTRANSCODE(strReasonCode);
			callInfo.setDISPOSITION("XA");
			callInfo.setCALLENDREASON("TRANSFER");
			
			traceinfo.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "callInfo:UUI: "+ callInfo.getUUIDATA());
			ivrreportdata.setCALLINFO(callInfo);
			
			if(transferVDNInfo.getTransferVDN1()==null){
				 strCircle			= mySession.getVariableField(IProjectVariables.CALL_DATA, IProjectVariables.CALL_DATA_FIELD_CIRCLE).getStringValue();
				 strLanguage		= mySession.getVariableField(IProjectVariables.CALL_DATA, IProjectVariables.CALL_DATA_FIELD_CURRENT_LANG).getStringValue();
				System.out.println(strCircle);
				System.out.println(strLanguage);
				String strTransferVDNKey = strCircle+IVRConstants.UNDER_SCORE+strLanguage+IVRConstants.UNDER_SCORE+IVRConstants.TRANSFER_VDN;
				strTransferVDN = ivrProp.getProperty(mySession,strTransferVDNKey);
				traceinfo.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "Transfer VDNKEY"+strTransferVDNKey);
				traceinfo.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "Transfer VDN"+strTransferVDN);
				if(strTransferVDN==null)
				{
					strTransferVDN=ivrProp.getProperty(mySession,IVRConstants.DEFAULT_TRANSFERVDN);
					traceinfo.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "Transfer VDN2"+strTransferVDN);
				}
					
				mySession.getVariableField(IProjectVariables.CALL_DATA, IProjectVariables.CALL_DATA_FIELD_TRANSFER_VDN).setValue(strTransferVDN);
				callInfo.setAGENTEXTN(strTransferVDN);
				callInfo.setAGENTID(strTransferVDN);
				callInfo.setTRANSFERVDN(strTransferVDN);
			}
			else{
				mySession.getVariableField(IProjectVariables.CALL_DATA, IProjectVariables.CALL_DATA_FIELD_TRANSFER_VDN).setValue(transferVDNInfo.getTransferVDN1());
				
			}
			
			traceinfo.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "Transfer VDN from DB"+transferVDNInfo.toString());
			
		}catch(Exception e){
			traceinfo.writeln(ITraceInfo.TRACE_LEVEL_ERROR, "Exception occured in Dat_GetTransferVDN.java" + e.getMessage());
			StackTrace.PrintException(e);
		}
		
			
	}


			
			/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2017-JUL-27  12:38:48 PM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(4);
		actions.add(new com.avaya.sce.runtime.varoperations.PrepareAAI("Shared", "session:ucid", "CallData:UUIData", "TransferUUIData").setDebugId(33));
		actions.add(new com.avaya.sce.runtime.tracking.TraceInfo(com.avaya.sce.runtimecommon.ITraceInfo.TRACE_LEVEL_DEBUG, "UUI Data Sent ::", "TransferUUIData").setDebugId(34));
		actions.add(new com.avaya.sce.runtime.tracking.TraceInfo(com.avaya.sce.runtimecommon.ITraceInfo.TRACE_LEVEL_DEBUG, "Transfer VDN ::", "CallData:transferVDN").setDebugId(35));
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
}
