package flow;

import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;
import com.rcom.bb.model.BANDetails;
import com.rcom.bb.model.FLPInfo;
import com.rcom.bb.resource.IVRDBServiceInstance;
import com.rcom.broadband.Constants;
import com.rcom.broadband.StackTrace;
import com.servion.util.IVRDataBean;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2015-MAY-29  05:54:16 PM
 */
public class CallFromRelianceFLP extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2015-MAY-29  05:54:16 PM
	 */
	public CallFromRelianceFLP() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	@Override
	public void requestBegin(SCESession mySession) {
	
		String ANI = null;
		boolean isFLP = false;
		String FLPFlag = null;
		IVRDataBean ivrDataBean = null;
		
		String BAN = null;
		String mobilePhone = null;
		String workPhone = null;
		String subscriberId = null;
		
		
		try
		{
		
			ITraceInfo trace = mySession.getTraceOutput();
			ANI = mySession.getVariableField(IProjectVariables.SESSION, IProjectVariables.SESSION_FIELD_ANI).getStringValue();
			
			/** getting the IVRData bean from session**/
			ivrDataBean = (IVRDataBean) mySession.getProperty(Constants.IVR_DATA_BEAN);
			
			
			FLPInfo flpInfo = new FLPInfo();
			flpInfo.setFLP(ANI);
			
			flpInfo = IVRDBServiceInstance.getInstance().getFLPInfo(ivrDataBean, flpInfo);
			FLPFlag = flpInfo.getFlag();
			trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "FLP Flag : " +FLPFlag);
			
			if(FLPFlag != null && !Constants.EMPTY.equalsIgnoreCase(FLPFlag) && (FLPFlag.equalsIgnoreCase(Constants.FLP)))
			{
				isFLP = true;
				
				trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "Since caller is calling from reliance FLP, trying to fetch BAN.");
				
				mySession.getVariableField(IProjectVariables.APP_VARIABLES, IProjectVariables.APP_VARIABLES_FIELD_POTSBIA__INPUT).setValue(ANI);
				
				BANDetails banDetails = new BANDetails();
				
				banDetails.setCli(ANI);
				
				banDetails = IVRDBServiceInstance.getInstance().getBanDetails(ivrDataBean, banDetails);
				BAN = banDetails.getBan();
				mobilePhone = banDetails.getMobilePhone();
				workPhone = banDetails.getWorkPhone();
				trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "BAN : " +BAN);
				trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "Mobile Phone : " +mobilePhone);
				trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "Work Phone : " +workPhone);
				trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "Subscriber ID : " +subscriberId);
				if(BAN != null && !Constants.EMPTY.equalsIgnoreCase(BAN))
				{
					
					mySession.getVariableField(IProjectVariables.APP_VARIABLES, IProjectVariables.APP_VARIABLES_FIELD_BAN).setValue(BAN);
					
					mySession.getVariableField(IProjectVariables.APP_VARIABLES, IProjectVariables.APP_VARIABLES_FIELD_CBB__INPUT).setValue(BAN);
					
					mySession.getVariableField(IProjectVariables.APP_VARIABLES, IProjectVariables.APP_VARIABLES_FIELD_MOBILE_NO).setValue(mobilePhone);
					mySession.getVariableField(IProjectVariables.APP_VARIABLES, IProjectVariables.APP_VARIABLES_FIELD_WORK_PHONE).setValue(workPhone);
					mySession.getVariableField(IProjectVariables.APP_VARIABLES, IProjectVariables.APP_VARIABLES_FIELD_SUBSCRIBER_ID).setValue(subscriberId);
					
				}
				else
				{
					isFLP = false;
				}
				
			}
			else
			{
				isFLP = false;
			}
			
			mySession.getVariableField(IProjectVariables.APP_VARIABLES, IProjectVariables.APP_VARIABLES_FIELD_IS_CALL_FROM_RELIANCE_FLP).setValue(isFLP);
			
		}catch(Exception e)
		{
			StackTrace.PrintException(e);
			mySession.getVariableField(IProjectVariables.APP_VARIABLES, IProjectVariables.APP_VARIABLES_FIELD_IS_CALL_FROM_RELIANCE_FLP).setValue(false);
		}
	}
	
	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2016-SEP-28  04:13:57 PM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = null;
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2016-SEP-28  04:13:57 PM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2016-SEP-28  04:13:57 PM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition1", "appVariables:IsCallFromRelianceFLP", com.avaya.sce.runtime.Expression.IS_TRUE).setDebugId(8729)).evaluate(mySession)) {

			if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition2", "appVariables:serviceType", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "constants:ServiceType_Postpaid", true).setDebugId(9089)).evaluate(mySession)) {
				actions = new java.util.ArrayList(1);
				actions.add(new com.avaya.sce.runtime.Next("setHotFlash_AccInfo", "(Postpaid)").setDebugId(8731));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			} else {
				actions = new java.util.ArrayList(1);
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("appVariables:fromPrepaidMenu", "true", true).setDebugId(12110));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

				if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition3", "appVariables:IsSouthCircle", com.avaya.sce.runtime.Expression.IS_TRUE).setDebugId(12661)).evaluate(mySession)) {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.Next("Prepaid_MN", "(Prepaid South)").setDebugId(9093));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				} else {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.Next("Prepaid_MN", "(Prepaid Other)").setDebugId(12663));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;
				}

			}


		} else {
			actions = new java.util.ArrayList(1);
			actions.add(new com.avaya.sce.runtime.Next("KnowCaller_MN", "(Account Info Contd)").setDebugId(8728));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;
		}


		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
}
