package flow.subflow.TVP_Process;

import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;
import com.hp.utilities.IVRConstants;
import com.hp.utilities.TVP_Properties;

import flow.IProjectVariables;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2016-SEP-28  12:13:03 PM
 */
public class Dat_CheckPOATypeConfig extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2016-SEP-28  12:13:03 PM
	 */
	public Dat_CheckPOATypeConfig() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2017-JUL-12  01:45:40 PM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = null;
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2017-JUL-12  01:45:40 PM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2017-JUL-12  01:45:40 PM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition1", "TVP_VARs:Java_Error", com.avaya.sce.runtime.Expression.IS_TRUE).setDebugId(521)).evaluate(mySession)) {
			actions = new java.util.ArrayList(1);
			actions.add(new com.avaya.sce.runtime.Next("TVP_Process-Ret_Xfer", "Exception").setDebugId(522));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

		}


		if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition2", "TVP_VARs:isPOATypeConfigured", com.avaya.sce.runtime.Expression.IS_TRUE).setDebugId(515)).evaluate(mySession)) {
			actions = new java.util.ArrayList(1);
			actions.add(new com.avaya.sce.runtime.Next("TVP_Process-Mnu_POAType", "Mnu").setDebugId(516));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

		} else {
			actions = new java.util.ArrayList(1);
			actions.add(new com.avaya.sce.runtime.Next("TVP_Process-Ret_Xfer", "Transfer").setDebugId(510));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;
		}


		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}

	@Override
	public void requestBegin(SCESession mySession) {
		
		String configFilePath				= IVRConstants.EMPTY_QUOTES;
		TVP_Properties TVP_Prop 			= null;
		String POAType,POASubmited 			= IVRConstants.EMPTY_QUOTES;
		String[] poaArr						= null;	
		ITraceInfo itraceInfo				= null;
		Boolean flag						= IVRConstants.FALSE;
		Boolean error						= IVRConstants.FALSE;	
		try
		{
		itraceInfo              = mySession.getTraceOutput();
		configFilePath 	= mySession.getVariableField(IProjectVariables.VAR__CONFIG,IProjectVariables.VAR__CONFIG_FIELD_CONFIG_FILE_PATH).getStringValue();
		itraceInfo.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "configFilePath: "+configFilePath );
		POASubmited				= mySession.getVariableField(IProjectVariables.TIBCO__VALIDATION__RES,IProjectVariables.TIBCO__VALIDATION__RES_FIELD_POATYPE).getStringValue();
		TVP_Prop 				= TVP_Properties.getInstance(configFilePath, mySession);	
		POAType					= TVP_Prop.getProperty(mySession,IVRConstants.POAType).trim();
		itraceInfo.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "POAType Configured: "+POAType );
		itraceInfo.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "POASubmited: "+POASubmited );
		poaArr  				= POAType.split(",");
		for(int i =0;i<poaArr.length;i++)
		{
			if((poaArr[i].toLowerCase()).contains(POASubmited.toLowerCase())){
				itraceInfo.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "POA Matched" );	
				  flag =true;
					break;
			}
		}
		}
		catch(Exception e)
		{
			itraceInfo.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "Exception in CheckPOATypeConfig.jave "+e.getMessage());
			error = IVRConstants.TRUE;
		}
		finally
		{
			mySession.getVariableField(IProjectVariables.TVP__VARS,IProjectVariables.TVP__VARS_FIELD_JAVA__ERROR).setValue(error);
			mySession.getVariableField(IProjectVariables.TVP__VARS,IProjectVariables.TVP__VARS_FIELD_IS_POATYPE_CONFIGURED).setValue(flag);
			itraceInfo.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "POATypeConfigured :: "+flag);
			itraceInfo.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "Error :: "+error);
		}
	}
	
	
}
