package english.phrasesets;

import com.avaya.sce.runtime.Phrase;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.hp.utilities.IVRConstants;

import flow.IProjectVariables;

/**
 * This phraseset class will be automatically populated with data from the 
 * phraseset project file.  Manual edits should only be outside of the tag 
 * areas or overridden methods. 
 * Class created on: 
 * Last generated by Orchestration Designer at: 2015-NOV-20  06:40:49 PM
 */
public class RCOM_TVP_PhraseSetEng extends com.avaya.sce.runtime.Phraseset { 

	//{{START:CLASS:FIELDS
	private static final com.avaya.sce.runtime.Phraseset.PhraseMap PHRASE_MAP;
	//}}END:CLASS:FIELDS

	/**
	 * Static initializer
	 */
	
	@Override
	public Phrase hookGetPhrase(String phraseName, Phrase phrase)
    {
           
           final Phrase orgPhrase = phrase;

           Phrase newPhrase = new Phrase()
           {
                  ITraceInfo itraceInfo;
                  public String getURL()
                  {
                        
                        final String audioURL = this.getMySession().getVariableField(IProjectVariables.VAR__PHRASES, IProjectVariables.VAR__PHRASES_FIELD_STATIC__URL).getStringValue();
                        System.out.print("Static Url"+audioURL);
                        String lang_Code = this.getMySession().getVariableField(IProjectVariables.CALL_INFO, IProjectVariables.CALL_INFO_FIELD_CURRENT_LANGUAGE).getStringValue();
                        if((lang_Code == null) || (lang_Code.isEmpty())) {
                               lang_Code = "ENG";
                        }
                      //  itraceInfo.writeln(ITraceInfo.TRACE_LEVEL_DEBUG,"Static URL :: " +audioURL, mySession);
                        //itraceInfo.writeln(ITraceInfo.TRACE_LEVEL_DEBUG,  "Static URL :: " +audioURL);
                        System.out.println("#Returning RCOM_TVP_PhraseSet:"+ audioURL + lang_Code + IVRConstants.SLASH + IVRConstants.STATIC + IVRConstants.SLASH + orgPhrase.getFileName());
                        return  audioURL + lang_Code + IVRConstants.SLASH + IVRConstants.STATIC + IVRConstants.SLASH + orgPhrase.getFileName();
                  }
           };
           return newPhrase;
    }
	static {
		//{{START:PHRASESET:STATIC

		// Create the phrase map, then populate with phrases
		PHRASE_MAP = new com.avaya.sce.runtime.Phraseset.PhraseMap(2);
		com.avaya.sce.runtime.Phrase phrase;

		// phrase: 45000
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.RCOM_TVP_PhraseSetEng.urlbase", "45000", "45000.wav", "Welcome to Reliacne Televerification"); 

		//}}END:PHRASESET:STATIC
	}
	/**
	 * Returns the Phrase with the given name.  To override the
	 * behavior and dynamically return a different Phrase object,
	 * override the method "hookGetPhrase(...)".
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2017-JUL-12  01:45:45 PM
	 * @see com.avaya.sce.runtime.Phraseset#getPhrase(String) 
	 */ 
	public com.avaya.sce.runtime.Phrase getPhrase(String phraseName) {
		return(getPhrase(RCOM_TVP_PhraseSetEng.PHRASE_MAP, phraseName));
	}
}
