package flow;

import java.util.ArrayList;

import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;
import com.servion.postpaid.utils.Constants;
import com.servion.postpaid.utils.DynamicMenu;
import com.servion.postpaid.utils.PrintStackTrace;
import com.servion.util.AppProperties;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2015-JUN-01  07:42:48 PM
 */
public class Initialize_MN_0043 extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS
	
	@Override
	public void requestBegin(SCESession mySession) {
		super.requestBegin(mySession);
		
		/*Declaring variables*/
		ITraceInfo info = null;
		String strReginalLanguage = null;
		String strReginalLanguageAudio = null;
		String strInitialAudio = null;
		String strcircleLanguages = "";
		String[] arrLanguages = null;
		AppProperties audioConfigInstance = null;
		DynamicMenu dynamicMenu = null;
		ArrayList<String> dynamicList = null;
		String strApplicationName = "", strCurrentLanguage = "";
		
		try {
			
			info = mySession.getTraceOutput();
			dynamicList = new ArrayList<String>();
			dynamicMenu = new DynamicMenu();
			
			/*Getting call data from session*/
			audioConfigInstance = (AppProperties) mySession.getProperty(Constants.AudioPropertyInstance);
			strApplicationName = mySession.getVariableField(IProjectVariables.CALL_DATA, IProjectVariables.CALL_DATA_FIELD_APPLICATION_NAME).getStringValue();
			
			strReginalLanguage = mySession.getVariableField(IProjectVariables.ROUTING_INFO, IProjectVariables.ROUTING_INFO_FIELD_CIRCLE_LANGUAGES).getStringValue();
			strCurrentLanguage = mySession.getCurrentLanguage();
			strReginalLanguage = strReginalLanguage.replaceAll(Constants.COMMA+strCurrentLanguage, "");
			strReginalLanguage = strReginalLanguage.replaceAll(strCurrentLanguage+Constants.COMMA, "");
			arrLanguages = strReginalLanguage.split(",");
			strInitialAudio = audioConfigInstance.getIVRProp(strApplicationName+Constants.HYPEN+Constants.MN_0043);
			
			
			info.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "--->Initial Audio from config:"+strInitialAudio);
			info.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "--->Reginal Language List:"+strReginalLanguage);
			
			
			/*Framing Language selection menu*/
			for (int i = 0; i < arrLanguages.length; i++) {
				strInitialAudio = strInitialAudio.replaceAll("L"+i,  arrLanguages[i]);
				dynamicList.add(audioConfigInstance.getIVRProp(arrLanguages[i]));
			}
			info.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "--->Initial Audio before processing:"+strInitialAudio);
			
			strInitialAudio = dynamicMenu.playPrompt(dynamicList, strInitialAudio, ""+dynamicList.size(), info);
			
			info.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "--->Initial Audio after processing:"+strInitialAudio);
			
			mySession.getVariableField(IProjectVariables.DMPROPERTIES, IProjectVariables.DMPROPERTIES_FIELD_INITIAL_AUDIOS).setValue(strInitialAudio);
			mySession.getVariableField(IProjectVariables.DMPROPERTIES, IProjectVariables.DMPROPERTIES_FIELD_MENU_OPTIONS).setValue(strReginalLanguage);
			mySession.getVariableField(IProjectVariables.DMPROPERTIES, IProjectVariables.DMPROPERTIES_FIELD_MENU_OPTION_COUNT).setValue(arrLanguages.length);
			
		} catch (Exception e) {
			PrintStackTrace.PrintException(e);
		}
		
	}

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2015-JUN-01  07:42:48 PM
	 */
	public Initialize_MN_0043() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2015-NOV-08  05:50:16 PM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = new com.avaya.sce.runtime.Next("ChangeLanguage_MN_0043", "Default");
		next.setDebugId(2438);
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2015-NOV-08  05:50:16 PM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2015-NOV-08  05:50:16 PM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(3);
		actions.add(new com.avaya.sce.runtime.varoperations.Assign("CallData:globalMenuType", "Constants:MenuRepeat", false).setDebugId(3057));
		actions.add(new com.avaya.sce.runtime.varoperations.Assign("CallData:repeatTries", "0", true).setDebugId(3058));
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
}
