package flow.subflow.HotFlash;

import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;

import com.rcom.ppp.model.MDNHotFlashInfo;
import com.rcom.ppp.resource.IVRDBServiceInstance;
import com.servion.util.AppConstant;
import com.servion.util.IVRDataBean;
import com.servion.util.StackTrace;

import flow.IProjectVariables;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2015-DEC-09  11:34:38 AM
 */
public class SetHotFlashInfo extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2015-DEC-09  11:34:38 AM
	 */
	public SetHotFlashInfo() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2016-JAN-18  02:17:33 PM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = new com.avaya.sce.runtime.Next("HotFlash-Return", "Default");
		next.setDebugId(158);
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2016-JAN-18  02:17:33 PM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2016-JAN-18  02:17:33 PM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition1", "Flag:isMdnHotFlash", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "true", false).setDebugId(161)).evaluate(mySession)) {
			actions = new java.util.ArrayList(1);
			actions.add(new com.avaya.sce.runtime.Next("HotFlash-Get_HotFlash_Message", "SetMdnHotFlash").setDebugId(162));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

		}

		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
	
	@Override
	public void requestBegin(SCESession mySession) {
		
		IVRDataBean objIVRData = null;
		ITraceInfo trace =null;
		try{
			trace = mySession.getTraceOutput();
			objIVRData = (IVRDataBean) mySession.getProperty(AppConstant.IVRDATABEAN);
			String callerANI = mySession.getVariableField(IProjectVariables.APP_VARIABLES,IProjectVariables.APP_VARIABLES_FIELD_ANI).getStringValue();
			
			MDNHotFlashInfo mdnhost=new MDNHotFlashInfo();
			
			mdnhost.setMdn(callerANI);
			
			/**DB**/
			mdnhost=IVRDBServiceInstance.getInstance().checkMDNHotFlashFlag(objIVRData, mdnhost);
			
			trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG,"mdnhost Responce :"+mdnhost.toString());
			String mdn_status="";
			
			mdn_status=mdnhost.getP_MDN_MSG_OUT();
			
			if(mdn_status.equalsIgnoreCase("Y"))
			{
				mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_IS_MDN_HOT_FLASH).setValue("TRUE");
			}
			else
			{
				mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_IS_MDN_HOT_FLASH).setValue("FALSE");
			}
			
		}
		catch(Exception e){
			trace.writeln(ITraceInfo.TRACE_LEVEL_ERROR,"ERROR in set MDN Hot flash :"+e);
			mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_IS_MDN_HOT_FLASH).setValue("FALSE");
			StackTrace.PrintException(e);
		}
	}
}
