package flow;

/**
 * This interface is used to define the name of variables that are 
 * declared in the call flow.  All variables are defined as 
 * <code>public static final String</code>, which allows user-defined
 * code to reference variable names by the Java variable name.
 * Last generated by Orchestration Designer at: 2015-MAR-18  01:23:31 PM
 */
public interface IProjectVariables {





	//{{START:PROJECT:VARIABLES
	/**
	 * This is a reserved block of variable name definitions.
	 * The variable names defined here can be used as the key
	 * to get the <code>com.avaya.sce.runtime.Variable</code>
	 * from the <code>SCESession</code> at runtime.<br>
	 * 
	 * For example, given a variable name <code>phoneNum</code>,
	 * user-defined code should access the variable in this format:<PRE>
	 *   Variable phNum = mySession.getVariable(IProjectVariables.PHONE_NUM);
	 *   if ( phNum != null ) {
	 *        // do something with the variable
	 *   }</PRE>
	 * 
	 * This block of code is generated automatically by Orchestration Designer and should not
	 * be manually edited as changes may be overwritten by future code generation.
	 * Last generated by Orchestration Designer at: 2017-SEP-13  03:14:20 PM
	 */
	public static final String DMPROPERTIES = "DMProperties";
	public static final String LINK_DOWN__INRS__PA___0_0_1_0 = "LinkDown_INRS_PA_0010";
	public static final String ROAMING_SERVICE__INRS__MN___0_0_0_2 = "RoamingService_INRS_MN_0002";
	public static final String NOT_AUTHORIZED__INRS__PA___0_0_0_2 = "NotAuthorized_INRS_PA_0002";
	public static final String TRANSFER = "Transfer";
	public static final String REDIRECTINFO = "redirectinfo";
	public static final String TRANSFER_VDN_1 = "TransferVDN1";
	public static final String TRANSFER_VDN_2 = "TransferVDN2";
	public static final String WELCOME__INRS__PA___0_0_0_1 = "Welcome_INRS_PA_0001";
	public static final String LANGUAGE_SELECT__INRS__MN___0_0_0_1 = "LanguageSelect_INRS_MN_0001";
	public static final String CONSTANTS = "Constants";
	public static final String DATE = "date";
	public static final String TRANSFER__INRS__PA___0_0_0_5 = "Transfer_INRS_PA_0005";
	public static final String TRANSFER_CODE = "TransferCode";
	public static final String FLAG = "Flag";
	public static final String CALL_DATA = "CallData";
	public static final String OPTIONS = "Options";
	public static final String SESSION = "session";
	public static final String DD_LAST_EXCEPTION = "ddLastException";
	public static final String ROAMING__INRS__PA___0_0_0_3 = "Roaming_INRS_PA_0003";
	public static final String TIME = "time";
	public static final String SHAREDUUI = "shareduui";
	//}}END:PROJECT:VARIABLES
	//{{START:PROJECT:VARIABLEFIELDS
	public static final String DMPROPERTIES_FIELD_CONFIG_FILE_PATH = "configFilePath";
	public static final String DMPROPERTIES_FIELD_GLOBAL_PROPERTY = "globalProperty";
	public static final String DMPROPERTIES_FIELD_HINDI_CONFIG_FILE_PATH = "hindiConfigFilePath";
	public static final String DMPROPERTIES_FIELD_LANGUAGE_SELECT__INRS__MN___0_0_0_1 = "LanguageSelect_INRS_MN_0001";
	public static final String DMPROPERTIES_FIELD_LINK_DOWN__INRS__PA___0_0_1_0 = "LinkDown_INRS_PA_0010";
	public static final String DMPROPERTIES_FIELD_NOT_AUTHORIZED__INRS__PA___0_0_0_2 = "NotAuthorized_INRS_PA_0002";
	public static final String DMPROPERTIES_FIELD_ROAMING__INRS__PA___0_0_0_3 = "Roaming_INRS_PA_0003";
	public static final String DMPROPERTIES_FIELD_ROAMING_SERVICE__INRS__MN___0_0_0_2 = "RoamingService_INRS_MN_0002";
	public static final String DMPROPERTIES_FIELD_TRANSFER__INRS__PA___0_0_0_5 = "Transfer_INRS_PA_0005";
	public static final String DMPROPERTIES_FIELD_WELCOME__INRS__PA___0_0_0_1 = "Welcome_INRS_PA_0001";
	public static final String LINK_DOWN__INRS__PA___0_0_1_0_FIELD_ANNOUNCE_ID = "AnnounceID";
	public static final String LINK_DOWN__INRS__PA___0_0_1_0_FIELD_CONFIDENCE = "Confidence";
	public static final String LINK_DOWN__INRS__PA___0_0_1_0_FIELD_CONFIRMATION_REMAINING = "ConfirmationRemaining";
	public static final String LINK_DOWN__INRS__PA___0_0_1_0_FIELD_DIALOG_NAME = "DialogName";
	public static final String LINK_DOWN__INRS__PA___0_0_1_0_FIELD_INPUT_TYPE = "InputType";
	public static final String LINK_DOWN__INRS__PA___0_0_1_0_FIELD_MENU_END_TIME = "MenuEndTime";
	public static final String LINK_DOWN__INRS__PA___0_0_1_0_FIELD_MENU_ID = "MenuID";
	public static final String LINK_DOWN__INRS__PA___0_0_1_0_FIELD_MENU_START_TIME = "MenuStartTime";
	public static final String LINK_DOWN__INRS__PA___0_0_1_0_FIELD_N_BEST_VALUES = "nBestValues";
	public static final String LINK_DOWN__INRS__PA___0_0_1_0_FIELD_NOINPUT_REMAINING = "NoinputRemaining";
	public static final String LINK_DOWN__INRS__PA___0_0_1_0_FIELD_NOMATCH_REMAINING = "NomatchRemaining";
	public static final String LINK_DOWN__INRS__PA___0_0_1_0_FIELD_OTHER_SLOT = "OtherSlot";
	public static final String LINK_DOWN__INRS__PA___0_0_1_0_FIELD_RECORDED__UTTERANCE = "Recorded_Utterance";
	public static final String LINK_DOWN__INRS__PA___0_0_1_0_FIELD_RETURN_CODE = "ReturnCode";
	public static final String LINK_DOWN__INRS__PA___0_0_1_0_FIELD_SPECIFIC_SLOT = "SpecificSlot";
	public static final String LINK_DOWN__INRS__PA___0_0_1_0_FIELD_UTTERANCE = "Utterance";
	public static final String LINK_DOWN__INRS__PA___0_0_1_0_FIELD_VALUE = "Value";
	public static final String ROAMING_SERVICE__INRS__MN___0_0_0_2_FIELD_ANNOUNCE_ID = "AnnounceID";
	public static final String ROAMING_SERVICE__INRS__MN___0_0_0_2_FIELD_CONFIDENCE = "Confidence";
	public static final String ROAMING_SERVICE__INRS__MN___0_0_0_2_FIELD_CONFIRMATION_REMAINING = "ConfirmationRemaining";
	public static final String ROAMING_SERVICE__INRS__MN___0_0_0_2_FIELD_DIALOG_NAME = "DialogName";
	public static final String ROAMING_SERVICE__INRS__MN___0_0_0_2_FIELD_INPUT_TYPE = "InputType";
	public static final String ROAMING_SERVICE__INRS__MN___0_0_0_2_FIELD_MENU_END_TIME = "MenuEndTime";
	public static final String ROAMING_SERVICE__INRS__MN___0_0_0_2_FIELD_MENU_ID = "MenuID";
	public static final String ROAMING_SERVICE__INRS__MN___0_0_0_2_FIELD_MENU_START_TIME = "MenuStartTime";
	public static final String ROAMING_SERVICE__INRS__MN___0_0_0_2_FIELD_N_BEST_VALUES = "nBestValues";
	public static final String ROAMING_SERVICE__INRS__MN___0_0_0_2_FIELD_NOINPUT_REMAINING = "NoinputRemaining";
	public static final String ROAMING_SERVICE__INRS__MN___0_0_0_2_FIELD_NOMATCH_REMAINING = "NomatchRemaining";
	public static final String ROAMING_SERVICE__INRS__MN___0_0_0_2_FIELD_OTHER_SLOT = "OtherSlot";
	public static final String ROAMING_SERVICE__INRS__MN___0_0_0_2_FIELD_RECORDED__UTTERANCE = "Recorded_Utterance";
	public static final String ROAMING_SERVICE__INRS__MN___0_0_0_2_FIELD_RETURN_CODE = "ReturnCode";
	public static final String ROAMING_SERVICE__INRS__MN___0_0_0_2_FIELD_SPECIFIC_SLOT = "SpecificSlot";
	public static final String ROAMING_SERVICE__INRS__MN___0_0_0_2_FIELD_UTTERANCE = "Utterance";
	public static final String ROAMING_SERVICE__INRS__MN___0_0_0_2_FIELD_VALUE = "Value";
	public static final String NOT_AUTHORIZED__INRS__PA___0_0_0_2_FIELD_ANNOUNCE_ID = "AnnounceID";
	public static final String NOT_AUTHORIZED__INRS__PA___0_0_0_2_FIELD_CONFIDENCE = "Confidence";
	public static final String NOT_AUTHORIZED__INRS__PA___0_0_0_2_FIELD_CONFIRMATION_REMAINING = "ConfirmationRemaining";
	public static final String NOT_AUTHORIZED__INRS__PA___0_0_0_2_FIELD_DIALOG_NAME = "DialogName";
	public static final String NOT_AUTHORIZED__INRS__PA___0_0_0_2_FIELD_INPUT_TYPE = "InputType";
	public static final String NOT_AUTHORIZED__INRS__PA___0_0_0_2_FIELD_MENU_END_TIME = "MenuEndTime";
	public static final String NOT_AUTHORIZED__INRS__PA___0_0_0_2_FIELD_MENU_ID = "MenuID";
	public static final String NOT_AUTHORIZED__INRS__PA___0_0_0_2_FIELD_MENU_START_TIME = "MenuStartTime";
	public static final String NOT_AUTHORIZED__INRS__PA___0_0_0_2_FIELD_N_BEST_VALUES = "nBestValues";
	public static final String NOT_AUTHORIZED__INRS__PA___0_0_0_2_FIELD_NOINPUT_REMAINING = "NoinputRemaining";
	public static final String NOT_AUTHORIZED__INRS__PA___0_0_0_2_FIELD_NOMATCH_REMAINING = "NomatchRemaining";
	public static final String NOT_AUTHORIZED__INRS__PA___0_0_0_2_FIELD_OTHER_SLOT = "OtherSlot";
	public static final String NOT_AUTHORIZED__INRS__PA___0_0_0_2_FIELD_RECORDED__UTTERANCE = "Recorded_Utterance";
	public static final String NOT_AUTHORIZED__INRS__PA___0_0_0_2_FIELD_RETURN_CODE = "ReturnCode";
	public static final String NOT_AUTHORIZED__INRS__PA___0_0_0_2_FIELD_SPECIFIC_SLOT = "SpecificSlot";
	public static final String NOT_AUTHORIZED__INRS__PA___0_0_0_2_FIELD_UTTERANCE = "Utterance";
	public static final String NOT_AUTHORIZED__INRS__PA___0_0_0_2_FIELD_VALUE = "Value";
	public static final String REDIRECTINFO_FIELD_PRESENTATIONINFO = "presentationinfo";
	public static final String REDIRECTINFO_FIELD_REASON = "reason";
	public static final String REDIRECTINFO_FIELD_SCREENINGINFO = "screeninginfo";
	public static final String REDIRECTINFO_FIELD_URI = "uri";
	public static final String WELCOME__INRS__PA___0_0_0_1_FIELD_ANNOUNCE_ID = "AnnounceID";
	public static final String WELCOME__INRS__PA___0_0_0_1_FIELD_CONFIDENCE = "Confidence";
	public static final String WELCOME__INRS__PA___0_0_0_1_FIELD_CONFIRMATION_REMAINING = "ConfirmationRemaining";
	public static final String WELCOME__INRS__PA___0_0_0_1_FIELD_DIALOG_NAME = "DialogName";
	public static final String WELCOME__INRS__PA___0_0_0_1_FIELD_INPUT_TYPE = "InputType";
	public static final String WELCOME__INRS__PA___0_0_0_1_FIELD_MENU_END_TIME = "MenuEndTime";
	public static final String WELCOME__INRS__PA___0_0_0_1_FIELD_MENU_ID = "MenuID";
	public static final String WELCOME__INRS__PA___0_0_0_1_FIELD_MENU_START_TIME = "MenuStartTime";
	public static final String WELCOME__INRS__PA___0_0_0_1_FIELD_N_BEST_VALUES = "nBestValues";
	public static final String WELCOME__INRS__PA___0_0_0_1_FIELD_NOINPUT_REMAINING = "NoinputRemaining";
	public static final String WELCOME__INRS__PA___0_0_0_1_FIELD_NOMATCH_REMAINING = "NomatchRemaining";
	public static final String WELCOME__INRS__PA___0_0_0_1_FIELD_OTHER_SLOT = "OtherSlot";
	public static final String WELCOME__INRS__PA___0_0_0_1_FIELD_RECORDED__UTTERANCE = "Recorded_Utterance";
	public static final String WELCOME__INRS__PA___0_0_0_1_FIELD_RETURN_CODE = "ReturnCode";
	public static final String WELCOME__INRS__PA___0_0_0_1_FIELD_SPECIFIC_SLOT = "SpecificSlot";
	public static final String WELCOME__INRS__PA___0_0_0_1_FIELD_UTTERANCE = "Utterance";
	public static final String WELCOME__INRS__PA___0_0_0_1_FIELD_VALUE = "Value";
	public static final String LANGUAGE_SELECT__INRS__MN___0_0_0_1_FIELD_ANNOUNCE_ID = "AnnounceID";
	public static final String LANGUAGE_SELECT__INRS__MN___0_0_0_1_FIELD_CONFIDENCE = "Confidence";
	public static final String LANGUAGE_SELECT__INRS__MN___0_0_0_1_FIELD_CONFIRMATION_REMAINING = "ConfirmationRemaining";
	public static final String LANGUAGE_SELECT__INRS__MN___0_0_0_1_FIELD_DIALOG_NAME = "DialogName";
	public static final String LANGUAGE_SELECT__INRS__MN___0_0_0_1_FIELD_INPUT_TYPE = "InputType";
	public static final String LANGUAGE_SELECT__INRS__MN___0_0_0_1_FIELD_MENU_END_TIME = "MenuEndTime";
	public static final String LANGUAGE_SELECT__INRS__MN___0_0_0_1_FIELD_MENU_ID = "MenuID";
	public static final String LANGUAGE_SELECT__INRS__MN___0_0_0_1_FIELD_MENU_START_TIME = "MenuStartTime";
	public static final String LANGUAGE_SELECT__INRS__MN___0_0_0_1_FIELD_N_BEST_VALUES = "nBestValues";
	public static final String LANGUAGE_SELECT__INRS__MN___0_0_0_1_FIELD_NOINPUT_REMAINING = "NoinputRemaining";
	public static final String LANGUAGE_SELECT__INRS__MN___0_0_0_1_FIELD_NOMATCH_REMAINING = "NomatchRemaining";
	public static final String LANGUAGE_SELECT__INRS__MN___0_0_0_1_FIELD_OTHER_SLOT = "OtherSlot";
	public static final String LANGUAGE_SELECT__INRS__MN___0_0_0_1_FIELD_RECORDED__UTTERANCE = "Recorded_Utterance";
	public static final String LANGUAGE_SELECT__INRS__MN___0_0_0_1_FIELD_RETURN_CODE = "ReturnCode";
	public static final String LANGUAGE_SELECT__INRS__MN___0_0_0_1_FIELD_SPECIFIC_SLOT = "SpecificSlot";
	public static final String LANGUAGE_SELECT__INRS__MN___0_0_0_1_FIELD_UTTERANCE = "Utterance";
	public static final String LANGUAGE_SELECT__INRS__MN___0_0_0_1_FIELD_VALUE = "Value";
	public static final String CONSTANTS_FIELD_ENG = "ENG";
	public static final String CONSTANTS_FIELD_HIN = "HIN";
	public static final String CONSTANTS_FIELD_INRS__TR___0_0_0_1 = "INRS_TR_0001";
	public static final String CONSTANTS_FIELD_INRS__TR___0_0_0_2 = "INRS_TR_0002";
	public static final String CONSTANTS_FIELD_SUCCESS = "success";
	public static final String CONSTANTS_FIELD_TAM = "TAM";
	public static final String CONSTANTS_FIELD_UNTITLED_3 = "untitled3";
	public static final String CONSTANTS_FIELD_UNTITLED_4 = "untitled4";
	public static final String CONSTANTS_FIELD_UNTITLED_5 = "untitled5";
	public static final String CONSTANTS_FIELD_UNTITLED_6 = "untitled6";
	public static final String DATE_FIELD_AUDIO = "audio";
	public static final String DATE_FIELD_DAYOFMONTH = "dayofmonth";
	public static final String DATE_FIELD_DAYOFWEEK = "dayofweek";
	public static final String DATE_FIELD_DAYOFWEEKNUM = "dayofweeknum";
	public static final String DATE_FIELD_DAYOFYEAR = "dayofyear";
	public static final String DATE_FIELD_MONTH = "month";
	public static final String DATE_FIELD_MONTHINYEAR = "monthinyear";
	public static final String DATE_FIELD_YEAR = "year";
	public static final String TRANSFER__INRS__PA___0_0_0_5_FIELD_ANNOUNCE_ID = "AnnounceID";
	public static final String TRANSFER__INRS__PA___0_0_0_5_FIELD_CONFIDENCE = "Confidence";
	public static final String TRANSFER__INRS__PA___0_0_0_5_FIELD_CONFIRMATION_REMAINING = "ConfirmationRemaining";
	public static final String TRANSFER__INRS__PA___0_0_0_5_FIELD_DIALOG_NAME = "DialogName";
	public static final String TRANSFER__INRS__PA___0_0_0_5_FIELD_INPUT_TYPE = "InputType";
	public static final String TRANSFER__INRS__PA___0_0_0_5_FIELD_MENU_END_TIME = "MenuEndTime";
	public static final String TRANSFER__INRS__PA___0_0_0_5_FIELD_MENU_ID = "MenuID";
	public static final String TRANSFER__INRS__PA___0_0_0_5_FIELD_MENU_START_TIME = "MenuStartTime";
	public static final String TRANSFER__INRS__PA___0_0_0_5_FIELD_N_BEST_VALUES = "nBestValues";
	public static final String TRANSFER__INRS__PA___0_0_0_5_FIELD_NOINPUT_REMAINING = "NoinputRemaining";
	public static final String TRANSFER__INRS__PA___0_0_0_5_FIELD_NOMATCH_REMAINING = "NomatchRemaining";
	public static final String TRANSFER__INRS__PA___0_0_0_5_FIELD_OTHER_SLOT = "OtherSlot";
	public static final String TRANSFER__INRS__PA___0_0_0_5_FIELD_RECORDED__UTTERANCE = "Recorded_Utterance";
	public static final String TRANSFER__INRS__PA___0_0_0_5_FIELD_RETURN_CODE = "ReturnCode";
	public static final String TRANSFER__INRS__PA___0_0_0_5_FIELD_SPECIFIC_SLOT = "SpecificSlot";
	public static final String TRANSFER__INRS__PA___0_0_0_5_FIELD_UTTERANCE = "Utterance";
	public static final String TRANSFER__INRS__PA___0_0_0_5_FIELD_VALUE = "Value";
	public static final String FLAG_FIELD_FORCED_END = "forcedEnd";
	public static final String FLAG_FIELD_LINK_DOWN = "linkDown";
	public static final String FLAG_FIELD_POSTPAID_FLAG = "postpaidFlag";
	public static final String CALL_DATA_FIELD_CIRCLE = "circle";
	public static final String CALL_DATA_FIELD_UUI_DATA = "uuiData";
	public static final String OPTIONS_FIELD_ONE = "one";
	public static final String OPTIONS_FIELD_THREE = "three";
	public static final String OPTIONS_FIELD_TWO = "two";
	public static final String SESSION_FIELD_AAI = "aai";
	public static final String SESSION_FIELD_ANI = "ani";
	public static final String SESSION_FIELD_CALLTAG = "calltag";
	public static final String SESSION_FIELD_CHANNEL = "channel";
	public static final String SESSION_FIELD_CHANNELTYPE = "channeltype";
	public static final String SESSION_FIELD_CONVERSEFIRST = "conversefirst";
	public static final String SESSION_FIELD_CONVERSESECOND = "conversesecond";
	public static final String SESSION_FIELD_CURRENTLANGUAGE = "currentlanguage";
	public static final String SESSION_FIELD_DNIS = "dnis";
	public static final String SESSION_FIELD_EXIT_CUSTOMER_ID = "exitCustomerId";
	public static final String SESSION_FIELD_EXIT_INFO_1 = "exitInfo1";
	public static final String SESSION_FIELD_EXIT_INFO_2 = "exitInfo2";
	public static final String SESSION_FIELD_EXIT_PREFERRED_PATH = "exitPreferredPath";
	public static final String SESSION_FIELD_EXIT_REASON = "exitReason";
	public static final String SESSION_FIELD_EXIT_TOPIC = "exitTopic";
	public static final String SESSION_FIELD_LASTERROR = "lasterror";
	public static final String SESSION_FIELD_MEDIATYPE = "mediatype";
	public static final String SESSION_FIELD_PROTOCOLNAME = "protocolname";
	public static final String SESSION_FIELD_PROTOCOLVERSION = "protocolversion";
	public static final String SESSION_FIELD_SESSIONID = "sessionid";
	public static final String SESSION_FIELD_SESSIONLABEL = "sessionlabel";
	public static final String SESSION_FIELD_SHAREDMODE = "sharedmode";
	public static final String SESSION_FIELD_UCID = "ucid";
	public static final String SESSION_FIELD_UUI = "uui";
	public static final String SESSION_FIELD_VIDEOBITRATE = "videobitrate";
	public static final String SESSION_FIELD_VIDEOCODEC = "videocodec";
	public static final String SESSION_FIELD_VIDEOENABLED = "videoenabled";
	public static final String SESSION_FIELD_VIDEOFARFMTP = "videofarfmtp";
	public static final String SESSION_FIELD_VIDEOFORMAT = "videoformat";
	public static final String SESSION_FIELD_VIDEOFPS = "videofps";
	public static final String SESSION_FIELD_VIDEOHEIGHT = "videoheight";
	public static final String SESSION_FIELD_VIDEONEARFMTP = "videonearfmtp";
	public static final String SESSION_FIELD_VIDEOWIDTH = "videowidth";
	public static final String SESSION_FIELD_VPCALLEDEXTENSION = "vpcalledextension";
	public static final String SESSION_FIELD_VPCONVERSEONDATA = "vpconverseondata";
	public static final String SESSION_FIELD_VPCOVERAGEREASON = "vpcoveragereason";
	public static final String SESSION_FIELD_VPCOVERAGETYPE = "vpcoveragetype";
	public static final String SESSION_FIELD_VPRDNIS = "vprdnis";
	public static final String SESSION_FIELD_VPREPORTURL = "vpreporturl";
	public static final String DD_LAST_EXCEPTION_FIELD_ERRORCODE = "errorcode";
	public static final String DD_LAST_EXCEPTION_FIELD_MESSAGE = "message";
	public static final String DD_LAST_EXCEPTION_FIELD_OBJECT = "object";
	public static final String DD_LAST_EXCEPTION_FIELD_STACKTRACE = "stacktrace";
	public static final String DD_LAST_EXCEPTION_FIELD_TYPE = "type";
	public static final String ROAMING__INRS__PA___0_0_0_3_FIELD_ANNOUNCE_ID = "AnnounceID";
	public static final String ROAMING__INRS__PA___0_0_0_3_FIELD_CONFIDENCE = "Confidence";
	public static final String ROAMING__INRS__PA___0_0_0_3_FIELD_CONFIRMATION_REMAINING = "ConfirmationRemaining";
	public static final String ROAMING__INRS__PA___0_0_0_3_FIELD_DIALOG_NAME = "DialogName";
	public static final String ROAMING__INRS__PA___0_0_0_3_FIELD_INPUT_TYPE = "InputType";
	public static final String ROAMING__INRS__PA___0_0_0_3_FIELD_MENU_END_TIME = "MenuEndTime";
	public static final String ROAMING__INRS__PA___0_0_0_3_FIELD_MENU_ID = "MenuID";
	public static final String ROAMING__INRS__PA___0_0_0_3_FIELD_MENU_START_TIME = "MenuStartTime";
	public static final String ROAMING__INRS__PA___0_0_0_3_FIELD_N_BEST_VALUES = "nBestValues";
	public static final String ROAMING__INRS__PA___0_0_0_3_FIELD_NOINPUT_REMAINING = "NoinputRemaining";
	public static final String ROAMING__INRS__PA___0_0_0_3_FIELD_NOMATCH_REMAINING = "NomatchRemaining";
	public static final String ROAMING__INRS__PA___0_0_0_3_FIELD_OTHER_SLOT = "OtherSlot";
	public static final String ROAMING__INRS__PA___0_0_0_3_FIELD_RECORDED__UTTERANCE = "Recorded_Utterance";
	public static final String ROAMING__INRS__PA___0_0_0_3_FIELD_RETURN_CODE = "ReturnCode";
	public static final String ROAMING__INRS__PA___0_0_0_3_FIELD_SPECIFIC_SLOT = "SpecificSlot";
	public static final String ROAMING__INRS__PA___0_0_0_3_FIELD_UTTERANCE = "Utterance";
	public static final String ROAMING__INRS__PA___0_0_0_3_FIELD_VALUE = "Value";
	public static final String TIME_FIELD_AUDIO = "audio";
	public static final String TIME_FIELD_HOUR = "hour";
	public static final String TIME_FIELD_MILLISECOND = "millisecond";
	public static final String TIME_FIELD_MINUTE = "minute";
	public static final String TIME_FIELD_SECOND = "second";
	public static final String TIME_FIELD_TIMEZONE = "timezone";
	public static final String SHAREDUUI_FIELD_ID = "id";
	public static final String SHAREDUUI_FIELD_VALUE = "value";
	//}}END:PROJECT:VARIABLEFIELDS
}
