package flow;

import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.IVariable;
import com.avaya.sce.runtimecommon.SCESession;
import com.dm.util.Constants;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2013-OCT-23  03:49:36 PM
 */
public class AssignPreviousIniitalPrmt extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2013-OCT-23  03:49:36 PM
	 */
	public AssignPreviousIniitalPrmt() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}


	@Override
	public void requestBegin(SCESession mySession) {

		ITraceInfo trace = mySession.getTraceOutput();
		IVariable inputVar = mySession.getVariable(IProjectVariables.INPUT_VARIABLES);
		String initialPrompt = inputVar.getComplexVariable().getField(IProjectVariables.INPUT_VARIABLES_FIELD_INITIAL_PROMPT).getStringValue();
		String moreOptionFlag = inputVar.getComplexVariable().getField(IProjectVariables.INPUT_VARIABLES_FIELD_MORE_OPTION_FLAG).getStringValue();
		String previousMenuFlag = inputVar.getComplexVariable().getField(IProjectVariables.INPUT_VARIABLES_FIELD_MORE_OPTION_PREVIOUS_MENU_FLAG).getStringValue();
		int counter = mySession.getVariableField(IProjectVariables.IDM__VARIABLES,IProjectVariables.IDM__VARIABLES_FIELD_MORE_OPTION_COUNT).getIntValue();

		if(mySession.isAppTraceEnabled())
		{
			trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "More Option Flag : " + moreOptionFlag);
			trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "Previous Menu Flag :" + previousMenuFlag);
		}
		
		try{
			if(moreOptionFlag.equalsIgnoreCase(Constants.TRUE)){
				if(previousMenuFlag.equalsIgnoreCase(Constants.TRUE)){					
					mySession.getVariableField(IProjectVariables.IDM__VARIABLES,IProjectVariables.IDM__VARIABLES_FIELD_MORE_OPTION_COUNT).setValue(counter);
					if(counter!=0){
						String[] prmt=initialPrompt.split("\\|");						
						if(mySession.isAppTraceEnabled()){mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "Previous Initial Prompt" + prmt[counter-1]);}
						mySession.getVariable(IProjectVariables.COLLECTIONPREVIOUSINIITALPROMPT).getSimpleVariable().setValue(prmt[counter-1]);
					}
					else{
						mySession.getVariableField(IProjectVariables.FLAGS,IProjectVariables.FLAGS_FIELD_MORE_OPTION_PREVIOUS_SET_FLAG).setValue(Constants.TRUE);
					}	
				}
			}
		}catch (Exception e) {
			e.printStackTrace();
		}
	}
	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2017-SEP-04  04:23:34 PM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = new com.avaya.sce.runtime.Next("CheckSuccessConfirmation", "More option flag is false");
		next.setDebugId(1526);
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2017-SEP-04  04:23:34 PM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2017-SEP-04  04:23:34 PM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition1", "inputVariables:moreOptionFlag", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "CONSTANTS:TRUE", true).setDebugId(1525)).evaluate(mySession)) {

			if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition2", "FLAGS:moreOptionPreviousSetFlag", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "CONSTANTS:TRUE", true).setDebugId(1591)).evaluate(mySession)) {
				actions = new java.util.ArrayList(1);
				actions.add(new com.avaya.sce.runtime.Next("CheckSuccessConfirmation", "No Previous").setDebugId(1592));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			}

			actions = new java.util.ArrayList(8);
			actions.add(new com.avaya.sce.runtime.varoperations.DeleteFromCollection("COLLECTIONINITIALPROMPT").setDebugId(2117));
			actions.add(new com.avaya.sce.runtime.varoperations.DeleteFromCollection("COLLECTIONINITIALREPROMPT").setDebugId(2116));
			actions.add(new com.avaya.sce.runtime.varoperations.Parse("COLLECTIONINITIALPROMPT", "COLLECTIONPREVIOUSINIITALPROMPT", "*", false).setDebugId(1594));
			actions.add(new com.avaya.sce.runtime.varoperations.Parse("COLLECTIONINITIALREPROMPT", "COLLECTIONPREVIOUSINIITALPROMPT", "*", false).setDebugId(1855));
			actions.add(new com.avaya.sce.runtime.varoperations.Parse("COLLECTIONMOREINITIALPRMTTEMP", "COLLECTIONPREVIOUSINIITALPROMPT", "*", false).setDebugId(2183));
			actions.add(new com.avaya.sce.runtime.tracking.TraceInfo(com.avaya.sce.runtimecommon.ITraceInfo.TRACE_LEVEL_DEBUG, "Counter Value after Previous", "IDM_Variables:moreOptionCount").setDebugId(1597));
			actions.add(new com.avaya.sce.runtime.tracking.TraceInfo(com.avaya.sce.runtimecommon.ITraceInfo.TRACE_LEVEL_DEBUG, "Collection initial prompt after previous", "COLLECTIONINITIALPROMPT").setDebugId(1595));
			actions.add(new com.avaya.sce.runtime.Next("IsConstraintListAvailable", "Previous").setDebugId(1521));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

		}

		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
}
