package flow.subflow.Locate_Retailer_and_Collect_Area_PIN_Code;

/**
 * This servlet is used to forward the request to the entry point of a
 * project callflow (subflow).
 * Last generated by Orchestration Designer at: 2015-MAY-26  07:01:12 PM
 */
public class GlobalPromptFeature extends com.avaya.sce.runtime.Subflow {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2015-MAY-26  07:01:12 PM
	 */
	public GlobalPromptFeature() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the name of the subflow that is being invoked.  This name is used for
	 * determining the URL mapping for the the entry point of the subflow..
	 *
	 * @return the name of the subflow
	 * Last generated by Orchestration Designer at: 2017-MAR-03  03:45:57 PM
	 */
	protected String getSubflowName() {
		return("GlobalFeaturePrompt");
	}
	/**
	 * Returns the name of the mapping of sub flow exit points to the URL mappings
	 * of the servlets to return back to in the calling flow.
	 *
	 * @return map of sub flow exit points to servlets in the calling flow.
	 * Last generated by Orchestration Designer at: 2017-MAR-03  03:45:57 PM
	 */
	protected java.util.Map<String,String> getExitPoints() {
		java.util.Map<String, String> exitPoints;
		exitPoints = new java.util.HashMap<String, String>();
		exitPoints.put("GlobalFeaturePrompt-agent", "Locate_Retailer_and_Collect_Area_PIN_Code-agent_transfer");
		exitPoints.put("GlobalFeaturePrompt-MainMenu", "Locate_Retailer_and_Collect_Area_PIN_Code-mainmenu");
		exitPoints.put("GlobalFeaturePrompt-PreviousMenu", "Locate_Retailer_and_Collect_Area_PIN_Code-previous");
		exitPoints.put("GlobalFeaturePrompt-Repeat", "Locate_Retailer_and_Collect_Area_PIN_Code-RetailerDetail_Annc");
		exitPoints.put("GlobalFeaturePrompt-thank_you", "Locate_Retailer_and_Collect_Area_PIN_Code-tries_exceed");
		return exitPoints;
	}
}
