package flow;

import java.util.ArrayList;

import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;
import com.rcom.ppp.model.IVRCspInfo;
import com.rcom.ppp.model.PhoneGenInfo;
import com.rcom.ppp.resource.IVRDBServiceInstance;
import com.servion.prepaid.report.GetReportObject;
import com.servion.prepaid.report.IVRREPORTDATA;
import com.servion.prepaid.report.IVRREPORTDATA.CALLINFO;
import com.servion.util.AppConstant;
import com.servion.util.AppProperties;
import com.servion.util.DynamicMenu;
import com.servion.util.IVRDataBean;
import com.servion.util.StackTrace;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2015-MAR-11  11:51:39 PM
 */
public class IVR_CSP_CustomerVal extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2015-MAR-11  11:51:39 PM
	 */
	public IVR_CSP_CustomerVal() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2017-JUL-05  10:39:05 AM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = null;
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2017-JUL-05  10:39:05 AM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2017-JUL-05  10:39:05 AM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition1", "appVariables:HostResult", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "constant:success", true).setDebugId(8613)).evaluate(mySession)) {
			actions = new java.util.ArrayList(2);
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("appVariables:HostResult", "constant:error", false).setDebugId(14832));
			actions.add(new com.avaya.sce.runtime.Next("LanguageMenu", "(SelectLang)").setDebugId(8619));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

		} else {
			actions = new java.util.ArrayList(2);
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("appVariables:transferReason", "TR_0003", true).setDebugId(14920));
			actions.add(new com.avaya.sce.runtime.Next("LinkDown", "(LinkDown)").setDebugId(8622));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;
		}


		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
	@Override
	public void requestBegin(SCESession mySession) {
		
		/** Declaration **/
		String  callerANI = AppConstant.EMPTY_STRING,preferedLang = AppConstant.EMPTY_STRING,propetyKey= AppConstant.EMPTY_STRING;
		String  barringCode = AppConstant.EMPTY_STRING,key = AppConstant.EMPTY_STRING,appName= AppConstant.EMPTY_STRING,propertiesLocation = AppConstant.EMPTY_STRING;
		String  callerType = AppConstant.EMPTY_STRING;
		String hostOutput = AppConstant.ERROR;
		IVRDataBean objIVRData = null;
		IVRCspInfo objIVRCspInfo = null;
		ITraceInfo trace =null;
		GetReportObject objGetReportObject = null;
		IVRREPORTDATA objIVRREPORTDATA= null;
		CALLINFO objCALLINFO = null;
		
		/**Assign**/
		trace = mySession.getTraceOutput();
		callerANI = mySession.getVariableField(IProjectVariables.APP_VARIABLES,IProjectVariables.APP_VARIABLES_FIELD_ANI).getStringValue();
		objIVRData = (IVRDataBean) mySession.getProperty(AppConstant.IVRDATABEAN);
		appName = mySession.getVariableField(IProjectVariables.APP_NAME).getStringValue();
		objIVRCspInfo = new IVRCspInfo();
		objIVRCspInfo.setMdn(callerANI);
		
		trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG,"caller ANI :"+callerANI);
		trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG,"IVRData Bean Object :"+objIVRData);
		trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG,"appName :"+appName);
		
		try{
		
		objGetReportObject = objIVRData.getGetReportObject(); 
		objIVRREPORTDATA = objGetReportObject.getIvrreportdata();
		objCALLINFO = objIVRREPORTDATA.getCALLINFO();
			
		/**DB**/
		objIVRCspInfo=IVRDBServiceInstance.getInstance().getIVRCSPInfo(objIVRData, objIVRCspInfo);
		
		/***Barring List **/
		barringCode=objIVRCspInfo.getBarringList();
		trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG,"Barring Code :"+barringCode);
		if(barringCode!=null && barringCode.contains(AppConstant.ABUSIVE))
			mySession.getVariableField(IProjectVariables.IVR__CSP__DETAILS,IProjectVariables.IVR__CSP__DETAILS_FIELD_BARRING_LIST).setValue(AppConstant.ABUSIVE);
		
		
		
		
		
		PhoneGenInfo phoneGenInfo = new PhoneGenInfo();
		phoneGenInfo.setMDN(callerANI);
		
		phoneGenInfo = IVRDBServiceInstance.getInstance().getPhoneGenInfo(objIVRData, phoneGenInfo);
		
		String serviceType = phoneGenInfo.getServiceType();
		
		trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "Service Type from DB :  :" +serviceType);
		
		/*
		 * If MDN is available in Phonegen, it will return its service type. If service type returned, it means MDN is RTN
		 */
		
		if(serviceType != null && serviceType.contains(AppProperties.GetInstance(AppConstant.IVR_CONFIG).getIVRProp(AppConstant.PREPAID_SERVICE_TYPE)))
		{
			mySession.getVariableField(IProjectVariables.IVR__CSP__DETAILS, IProjectVariables.IVR__CSP__DETAILS_FIELD_IS_PREPAID).setValue(true);
			mySession.getVariableField(IProjectVariables.IVR__CSP__DETAILS, IProjectVariables.IVR__CSP__DETAILS_FIELD_IS_POSTPAID).setValue(false);
			
			mySession.getVariableField(IProjectVariables.IVR__CSP__DETAILS, IProjectVariables.IVR__CSP__DETAILS_FIELD_RETENTION_LIST).setValue("RTN");
			
			if(serviceType!=null && serviceType.contains(AppConstant.CDMA)){
				callerType = AppConstant.CDMA;
			}else{
				callerType = AppConstant.GSM;
				mySession.getVariableField(IProjectVariables.FLAG, IProjectVariables.FLAG_FIELD_IS_GSMFLAG).setValue(AppConstant.Yes);
				
			}
			
		}
		else if(serviceType != null && serviceType.contains(AppProperties.GetInstance(AppConstant.IVR_CONFIG).getIVRProp(AppConstant.POSTPAID_SERVICE_TYPE)))
		{
			mySession.getVariableField(IProjectVariables.IVR__CSP__DETAILS, IProjectVariables.IVR__CSP__DETAILS_FIELD_IS_POSTPAID).setValue(true);
			mySession.getVariableField(IProjectVariables.IVR__CSP__DETAILS, IProjectVariables.IVR__CSP__DETAILS_FIELD_IS_PREPAID).setValue(false);
			
			mySession.getVariableField(IProjectVariables.IVR__CSP__DETAILS, IProjectVariables.IVR__CSP__DETAILS_FIELD_RETENTION_LIST).setValue("RTN");
			
			if(serviceType!=null && serviceType.contains(AppConstant.CDMA)){
				callerType = AppConstant.CDMA;
			}else{
				callerType = AppConstant.GSM;
				mySession.getVariableField(IProjectVariables.FLAG, IProjectVariables.FLAG_FIELD_IS_GSMFLAG).setValue(AppConstant.Yes);
				
			}
		}
		else
		{
			mySession.getVariableField(IProjectVariables.IVR__CSP__DETAILS, IProjectVariables.IVR__CSP__DETAILS_FIELD_IS_PREPAID).setValue(false);
			mySession.getVariableField(IProjectVariables.IVR__CSP__DETAILS, IProjectVariables.IVR__CSP__DETAILS_FIELD_IS_POSTPAID).setValue(false);
			
			mySession.getVariableField(IProjectVariables.IVR__CSP__DETAILS, IProjectVariables.IVR__CSP__DETAILS_FIELD_RETENTION_LIST).setValue("NA");
		}
		
		
		trace.writeln(ITraceInfo.TRACE_LEVEL_INFO,"RTN Value :"+mySession.getVariableField(IProjectVariables.IVR__CSP__DETAILS, IProjectVariables.IVR__CSP__DETAILS_FIELD_RETENTION_LIST).getStringValue());
		
		trace.writeln(ITraceInfo.TRACE_LEVEL_INFO,"Caller Type :"+callerType);
		mySession.getVariableField(IProjectVariables.APP_VARIABLES,IProjectVariables.APP_VARIABLES_FIELD_CALLER_TYPE).setValue(callerType);
		
		/**Retention List**//*
		if(phoneGenInfo.getRTN()!=null){
			trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "---> Retention :"+phoneGenInfo.getRTN());
			if(phoneGenInfo.getRTN().equalsIgnoreCase("RTN")){
				mySession.getVariableField(IProjectVariables.IVR__CSP__DETAILS, IProjectVariables.IVR__CSP__DETAILS_FIELD_RETENTION_LIST).setValue("RTN");
			}else{
				mySession.getVariableField(IProjectVariables.IVR__CSP__DETAILS, IProjectVariables.IVR__CSP__DETAILS_FIELD_RETENTION_LIST).setValue("NA");
			}
		}else{
			mySession.getVariableField(IProjectVariables.IVR__CSP__DETAILS, IProjectVariables.IVR__CSP__DETAILS_FIELD_RETENTION_LIST).setValue("NA");
		}*/
		
		trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG,"Language Selection Menu Inital Prompt Start");
		LanguageSelectionMenu(mySession);
		
		hostOutput = AppConstant.Success;
		
		
		}catch (Exception e) {
			trace.writeln(ITraceInfo.TRACE_LEVEL_ERROR, "Error in IVR CSP DB Hit :" +e);
			StackTrace.PrintException(e);
		}
		
		trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "Host Status :" +hostOutput);
		mySession.getVariableField(IProjectVariables.APP_VARIABLES,IProjectVariables.APP_VARIABLES_FIELD_HOST_RESULT).setValue(hostOutput);
	}
	
	public void LanguageSelectionMenu (SCESession mySession){
		
		/** Declaration **/
		String initialPrompt = AppConstant.EMPTY_STRING,grammarValue = AppConstant.EMPTY_STRING,circleLangCode = AppConstant.EMPTY_STRING;
		String dynamicWaves =  AppConstant.EMPTY_STRING,appName = AppConstant.EMPTY_STRING,key = AppConstant.EMPTY_STRING,circleLanguage = AppConstant.EMPTY_STRING,langKey = AppConstant.EMPTY_STRING;
		String[] arrayLangCode = null;
		ArrayList<String> arrLanguage=null;
		ITraceInfo trace =null;
		
		/**Assign**/
		trace = mySession.getTraceOutput();
		appName = mySession.getVariableField(IProjectVariables.APP_NAME).getStringValue();
		key = appName+AppConstant.SEPERATOR_HYPEN+AppConstant.MN_0001;
		
		trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG,"application Name :"+appName);
		trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG,"Language initial Prompt Key :"+key);
		
		dynamicWaves = AppProperties.GetInstance(AppConstant.DYN_MENU).getIVRProp(key);
		trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG,"Language initial Prompt :"+dynamicWaves);
		arrLanguage = new ArrayList<>();
		/** Form Dynamic Initial Prompt**/
		circleLangCode = mySession.getVariableField(IProjectVariables.APP_VARIABLES,IProjectVariables.APP_VARIABLES_FIELD_LANGUAGE_LIST).getStringValue();
		
		if(circleLangCode!=null){
			arrayLangCode = circleLangCode.split(AppConstant.SEPERATOR_COMMA);
			
			for(int i = 0;i<arrayLangCode.length;i++){
				/*key = AppConstant.Language_Code+arrayLangCode[i];
				trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG,"Language_Code Key:"+key);*/
				circleLanguage=arrayLangCode[i];
				trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG,"Circle Language : "+i+" :"+circleLanguage);
				langKey = AppConstant.LANG_+i;
				dynamicWaves = dynamicWaves.replaceAll(langKey,circleLanguage);
				trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG,"Dynamic Wave :" +dynamicWaves);
				arrLanguage.add(circleLanguage+AppConstant.wave);
			}
			
			/** Form Initial Prompt**/
			String count = String.valueOf(arrLanguage.size());
			initialPrompt=DynamicMenu.playPrompt(arrLanguage, dynamicWaves, count, AppConstant.MN_0001, trace);
			
			trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG,"Initial Prompt ::"+initialPrompt);
			trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG,"Menu Option : "+circleLangCode);
			
			mySession.getVariableField(IProjectVariables.DM_INPUT_PARAMETER,IProjectVariables.DM_INPUT_PARAMETER_FIELD_INITIAL_PROMPT).setValue(initialPrompt);
			mySession.getVariableField(IProjectVariables.DM_INPUT_PARAMETER,IProjectVariables.DM_INPUT_PARAMETER_FIELD_MORE_OPTION_COUNT).setValue(count);
			mySession.getVariableField(IProjectVariables.DM_INPUT_PARAMETER,IProjectVariables.DM_INPUT_PARAMETER_FIELD_MENU_OPTION).setValue(circleLangCode);
			
		}
		
	}
}
