package flow.subflow.PostpaidAccountInformation;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Hashtable;

import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;
import com.servion.rcom.ppp.hostinterface.view.ReqBillInfo;
import com.servion.rcom.ppp.hostinterface.view.ResBillInfo;
import com.servion.rcom.ppp.hostinterface.wrapper.IVRWebService;
import com.servion.rcom.ppp.hostinterface.wrapper.IVRWebServiceImpl;
import com.servion.util.AppConstant;
import com.servion.util.AppProperties;
import com.servion.util.IVRDataBean;
import com.servion.util.SetPushSMS;
import com.servion.util.StackTrace;

import flow.IProjectVariables;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2015-MAY-13  10:13:18 PM
 */
public class AccessHost_CheckBill extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS
	
	@Override
	public void requestBegin(SCESession mySession) {
		super.requestBegin(mySession);
		
		ITraceInfo info = mySession.getTraceOutput();
		
		IVRDataBean ivrDataBean = null;
		ReqBillInfo reqBillInfo = null;
		ResBillInfo resBillInfo = null;
		IVRWebService ivrWebService = null;
		String strBillDate = "", strDueDate = "";
		Date validationStartDate = null, billDate = null, dueDate = null;
		Date validationEndDate = null;
		Date callDate = null;
		long dateDiff = 0;
		
		SetPushSMS setPushSMS = null;
		String strSMSFrame = "";
		ArrayList<String> arrSMSData = null;
		Hashtable<String, String> smsHashTable = null;
		AppProperties appProperties = null;
		
		Calendar cal = Calendar.getInstance();
		DateFormat dateFormat = null;
		
		try {
			
			setPushSMS = new SetPushSMS();
			arrSMSData = new ArrayList<String>();
			
			callDate = new Date();
			dateFormat = new SimpleDateFormat("dd-MM-yyyy");
			
			ivrDataBean = (IVRDataBean) mySession.getProperty(AppConstant.IVRDATABEAN);
			reqBillInfo = new ReqBillInfo();
			if(mySession.getVariableField(IProjectVariables.IVR__CSP__DETAILS, IProjectVariables.IVR__CSP__DETAILS_FIELD_RETENTION_LIST).getStringValue().equalsIgnoreCase("RTN"))
			{
				reqBillInfo.setMDN(mySession.getVariableField(IProjectVariables.APP_VARIABLES, IProjectVariables.APP_VARIABLES_FIELD_ANI).getStringValue());
			}
			else
			{
				reqBillInfo.setMDN(mySession.getVariableField(IProjectVariables.APP_VARIABLES, IProjectVariables.APP_VARIABLES_FIELD_MOBILE_NO).getStringValue());
			}
			
			appProperties = AppProperties.GetInstance(AppConstant.IVR_CONFIG);

			ivrWebService = new IVRWebServiceImpl();
			resBillInfo = ivrWebService.executeBillInfo(ivrDataBean, reqBillInfo);
			
			mySession.getVariableField(IProjectVariables.CHECK_BILL_DETAIL, IProjectVariables.CREDIT_INFO_FIELD_RESPONSE_CODE).setValue(resBillInfo.getResponseCode());
			if((resBillInfo.getResponseCode()).equals(AppConstant.zero)){
				
				strDueDate = resBillInfo.getPaymentDueDate();
				dueDate = dateFormat.parse(strDueDate);
				
				strBillDate = resBillInfo.getBillIssueDate();
				billDate = dateFormat.parse(strBillDate);
				
				strBillDate = dateFormat.format(billDate);
				strDueDate = dateFormat.format(dueDate);
				
				dateFormat = new SimpleDateFormat("yyyy-MM-dd");
				mySession.getVariableField(IProjectVariables.CHECK_BILL_DETAIL, IProjectVariables.CHECK_BILL_DETAIL_FIELD_ACCOUNT_BALANCE).setValue(resBillInfo.getAccountBalance());
				mySession.getVariableField(IProjectVariables.CHECK_BILL_DETAIL, IProjectVariables.CHECK_BILL_DETAIL_FIELD_DUE_DATE).setValue(dateFormat.format(dueDate));
				mySession.getVariableField(IProjectVariables.CHECK_BILL_DETAIL, IProjectVariables.CHECK_BILL_DETAIL_FIELD_INVOICE_AMOUNT).setValue(resBillInfo.getInvoiceAmount());
				mySession.getVariableField(IProjectVariables.CHECK_BILL_DETAIL, IProjectVariables.CHECK_BILL_DETAIL_FIELD_ISSUE_DATE).setValue(dateFormat.format(billDate));
				
				dateFormat = new SimpleDateFormat("dd-MM-yyyy");
				
				dateDiff = dateFormat.parse(strBillDate).getTime() - callDate.getTime(); 
				dateDiff = (dateDiff / (24 * 60 * 60 * 1000))*24;
				
				mySession.getVariableField(IProjectVariables.CHECK_BILL_DETAIL, IProjectVariables.CHECK_BILL_DETAIL_FIELD_BILL_DATE_DIFF).setValue(dateDiff);
				
				cal.setTime(dateFormat.parse(strBillDate));
				cal.add(Calendar.DATE, 2);
				
				validationStartDate = cal.getTime();
				info.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "Validation Start Date:"+validationStartDate);
				
				cal.setTime(dateFormat.parse(strBillDate));
				cal.add(Calendar.DATE, 6);
				validationEndDate = cal.getTime();
				
				info.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "Validation End Date:"+validationEndDate);
				
				if((callDate.getTime()>=validationStartDate.getTime())&&(callDate.getTime()<=validationStartDate.getTime()))
					mySession.getVariableField(IProjectVariables.CHECK_BILL_DETAIL, IProjectVariables.CHECK_BILL_DETAIL_FIELD_IS_CALL_DATE_VALID).setValue(AppConstant.Yes);
				else
					mySession.getVariableField(IProjectVariables.CHECK_BILL_DETAIL, IProjectVariables.CHECK_BILL_DETAIL_FIELD_IS_CALL_DATE_VALID).setValue(AppConstant.No);
				
				arrSMSData.add(resBillInfo.getBillIssueDate());
				arrSMSData.add(resBillInfo.getInvoiceAmount());
				arrSMSData.add(resBillInfo.getAccountBalance());
				arrSMSData.add(resBillInfo.getPaymentDueDate());
				strSMSFrame = appProperties.getIVRProp(AppConstant.CHECK_BILL_Success);
				smsHashTable = setPushSMS.generatePushSMSDataMap(strSMSFrame, arrSMSData);
				
				info.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "Date Diff:"+dateDiff);
			}else{
				
				strSMSFrame = appProperties.getIVRProp(AppConstant.CHECK_BILL_Failure);
				smsHashTable = setPushSMS.generatePushSMSDataMap(strSMSFrame, arrSMSData);
				
				mySession.getVariableField(IProjectVariables.FLAG, IProjectVariables.FLAG_FIELD_IS_LINK_DOWN).setValue(AppConstant.Yes);
			}
			

		} catch (Exception e) {
			strSMSFrame = appProperties.getIVRProp(AppConstant.CHECK_BILL_Failure);
			smsHashTable = setPushSMS.generatePushSMSDataMap(strSMSFrame, arrSMSData);
			StackTrace.PrintException(e);
			
			mySession.getVariableField(IProjectVariables.FLAG, IProjectVariables.FLAG_FIELD_IS_LINK_DOWN).setValue(AppConstant.Yes);
		}finally{
			mySession.setProperty(AppConstant.SMSDataMap, smsHashTable);
			info.writeln(ITraceInfo.TRACE_LEVEL_INFO, "SMS HASH TABLE DATA BILL INFO: " +smsHashTable);
		}
	}

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2015-MAY-13  10:13:18 PM
	 */
	public AccessHost_CheckBill() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2017-JUL-05  10:39:11 AM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = null;
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2017-JUL-05  10:39:11 AM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2017-JUL-05  10:39:11 AM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(3);
		actions.add(new com.avaya.sce.runtime.varoperations.Assign("CallData:globalMenuType", "Constants:FeatureLevel", false).setDebugId(4412));
		actions.add(new com.avaya.sce.runtime.varoperations.Assign("CallData:repeatTries", "0", true).setDebugId(5304));
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition1", "Flag:isLinkDown", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "Constants:yes", true).setDebugId(1922)).evaluate(mySession)) {
			actions = new java.util.ArrayList(2);
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("appVariables:transferReason", "TR_0036", true).setDebugId(6364));
			actions.add(new com.avaya.sce.runtime.Next("PostpaidAccountInformation-Linkdown", "Linkdown").setDebugId(1928));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

		} else {
			actions = new java.util.ArrayList(1);
			actions.add(new com.avaya.sce.runtime.Next("PostpaidAccountInformation-CheckBillDateDiff", "CheckBillDateDiff").setDebugId(1924));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;
		}


		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
}
