package flow;

import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;
import com.rcom.otherflows.model.MDNHotFlashInfo;
import com.rcom.otherflows.resource.IVRDBServiceInstance;
import com.rcom.util.AppConstant;
import com.rcom.util.StackTrace;
import com.servion.util.AppProperties;
import com.servion.util.IVRDataBean;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2015-SEP-24  01:41:15 PM
 */
public class SetHotFlashInfo extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2015-SEP-24  01:41:15 PM
	 */
	public SetHotFlashInfo() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2017-MAR-24  10:30:18 AM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = new com.avaya.sce.runtime.Next("HotFlash", "HotFlash");
		next.setDebugId(3370);
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2017-MAR-24  10:30:18 AM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2017-MAR-24  10:30:18 AM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(2);
		actions.add(new com.avaya.sce.runtime.varoperations.Assign("HotFlashInfo:CallingNodeId", "Constants:Start", false).setDebugId(3371));
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition1", "Flag:is_MDN_hotflash", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "Constants:Key_true", true).setDebugId(6289)).evaluate(mySession)) {
			actions = new java.util.ArrayList(1);
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("HotFlashInfo:annoID", "appVariables:mdn_hotflashID", false).setDebugId(6290));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

		} else {
			actions = new java.util.ArrayList(1);
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("HotFlashInfo:annoID", "HotFlashIDs:RCD_PA_0002", false).setDebugId(3372));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;
		}


		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
	
	@Override
	public void requestBegin(SCESession mySession) {
	IVRDataBean objIVRData = null;
	ITraceInfo trace =null;
	String mdn_category = "",mdnHotflashCatagories = "",isMDNHotflah = AppConstant.FALSE;
	String MDN_Hotflash_Circle = "",Mdn_hotflash = AppConstant.FALSE;
	
	try{
		trace 			 	= mySession.getTraceOutput();
		objIVRData 		 	= (IVRDataBean) mySession.getProperty(AppConstant.IVRDATABEAN);
		String callerANI 	= mySession.getVariableField(IProjectVariables.SESSION,IProjectVariables.SESSION_FIELD_ANI).getStringValue();
		MDN_Hotflash_Circle = AppProperties.GetInstance(AppConstant.IVR_CONFIG).getIVRProp(AppConstant.CIRCLE_LIST);
         
         trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG,"MDN_Hotflash_Circle list :"+MDN_Hotflash_Circle.toString());
         	 	 
		 if(MDN_Hotflash_Circle==null||MDN_Hotflash_Circle.equalsIgnoreCase("N"))
		 {
			 MDN_Hotflash_Circle="NA";
		 }
		
		 String circleID  = mySession.getVariableField(IProjectVariables.APP_VARIABLES,IProjectVariables.APP_VARIABLES_FIELD_CIRCLE_ID).getStringValue();
		
		 if(MDN_Hotflash_Circle.contains(circleID))
			 {
			 
			  mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_MDN__HOTFLASH).setValue(AppConstant.TRUE); 
			  Mdn_hotflash = AppConstant.TRUE;
			  trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG,"Mdn_hotflash flag :"+Mdn_hotflash.toString());
			 }
	 
		 if(Mdn_hotflash.equalsIgnoreCase("TRUE"))
		 {
		
			 MDNHotFlashInfo mdnhost=new MDNHotFlashInfo();
			 mdnhost.setMdn(callerANI);
			 mdnhost.setAppID(AppProperties.GetInstance(AppConstant.IVR_CONFIG).getIVRProp(AppConstant.APP_NAME));
			 // *//**DB**//*
		    mdnhost=IVRDBServiceInstance.getIVRDBInstance().checkMDNHotFlashFlag(objIVRData, mdnhost);
		    trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG,"mdnhost Response :"+mdnhost.toString());
		
		    mdn_category = mdnhost.getStatus();
		
		trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG,"mdn_status12:"+mdn_category+"*");
		
		if(mdn_category!=null && !mdn_category.equalsIgnoreCase(AppConstant.EMPTY_STRING) && !mdn_category.equalsIgnoreCase(AppConstant.NA))
		{
		
					 isMDNHotflah = AppConstant.TRUE;
					 mySession.getVariableField(IProjectVariables.APP_VARIABLES,IProjectVariables.APP_VARIABLES_FIELD_MDN__HOTFLASH_ID).setValue( AppConstant.RCD_PA_0002+AppConstant.SEPERATOR_UNDERSCORE+mdn_category);
					 trace.writeln(ITraceInfo.TRACE_LEVEL_DEBUG,"MDN hotflash "+isMDNHotflah);
	 }
	 }
	}
	catch(Exception e){
		trace.writeln(ITraceInfo.TRACE_LEVEL_ERROR,"ERROR in set MDN Hot flash :"+e);
		mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_IS__MDN__HOTFLASH).setValue(AppConstant.FALSE);
		StackTrace.PrintException(e);
	}
	finally
	{
		mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_IS__MDN__HOTFLASH).setValue(isMDNHotflah);
	}
}
}
