package flow;

import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;
import com.rcom.postpaid.model.ValidateCWG;
import com.rcom.postpaid.resource.IVRDBServiceInstance;
import com.servion.postpaid.utils.Constants;
import com.servion.postpaid.utils.PrintStackTrace;
import com.servion.util.AppProperties;
import com.servion.util.IVRDataBean;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2015-APR-13  03:47:40 PM
 */
public class FetchCustomerProfile extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS
	@Override
	public void requestBegin(SCESession mySession) {
		super.requestBegin(mySession);
		
		/*Declaring the variables*/
		IVRDataBean ivrDataBean = null;
		ITraceInfo info = null;
		String strApplicationName = "", strPropertyFilePath = "", strReturnValue = "", strPropKey = "";
		AppProperties appProperties = null;
		ValidateCWG validateCWG = null;
		
		/*Assigning values to variables*/
		info = mySession.getTraceOutput();
		validateCWG = new ValidateCWG();
		validateCWG.setMdn(mySession.getVariableField(IProjectVariables.SESSION, IProjectVariables.SESSION_FIELD_ANI).getStringValue());
		appProperties = (AppProperties) mySession.getProperty(Constants.IvrPropertyInstance);
		
		/*Getting call data from sesion*/
		ivrDataBean = (IVRDataBean) mySession.getProperty(Constants.IVRDATABEAN);
		
		try {
			
			validateCWG = IVRDBServiceInstance.getInstance().validateCWGFlag(ivrDataBean, validateCWG);
			
			info.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "ValidateCWG :"+validateCWG.toString());
			
			if(validateCWG.getFlag() != null){
				if(validateCWG.getFlag().equalsIgnoreCase("CSPM")){
					mySession.getVariableField(IProjectVariables.FLAG, IProjectVariables.FLAG_FIELD_IS_CSPMHARDCODED).setValue(Constants.Yes);
				}else if(validateCWG.getFlag().equalsIgnoreCase("KDM")){
					mySession.getVariableField(IProjectVariables.FLAG, IProjectVariables.FLAG_FIELD_IS_KDMHARDCODED).setValue(Constants.Yes);
				}
			}
			
			/*
			Invoking the DB dip
			ivrCspInfo = IVRDBServiceInstance.getInstance().getIVRCSPInfo(ivrDataBean, ivrCspInfo);
			
			if(ivrCspInfo!=null){
				
				info.writeln(ITraceInfo.TRACE_LEVEL_DEBUG, "IVRCSP response:"+ivrCspInfo.toString());
				
				if(ivrCspInfo.getBarringList()!=null){
					if((ivrCspInfo.getBarringList()).contains("ABUSIVE")){
						mySession.getVariableField(IProjectVariables.CUSTOMER_PROFILE, IProjectVariables.CUSTOMER_PROFILE_FIELD_BARRING_LIST).setValue("ABUSIVE");
					}else{
						mySession.getVariableField(IProjectVariables.CUSTOMER_PROFILE, IProjectVariables.CUSTOMER_PROFILE_FIELD_BARRING_LIST).setValue("NA");
					}
				}
				else
					mySession.getVariableField(IProjectVariables.CUSTOMER_PROFILE, IProjectVariables.CUSTOMER_PROFILE_FIELD_BARRING_LIST).setValue("NA");
				
				mySession.getVariableField(IProjectVariables.CUSTOMER_PROFILE, IProjectVariables.CUSTOMER_PROFILE_FIELD_PREF_LANGUAGE).setValue(ivrCspInfo.getPreLang());
				if((ivrCspInfo.getPreLang()!=null)&&(!(ivrCspInfo.getPreLang().equalsIgnoreCase("NA")))){
					strApplicationName = mySession.getVariableField(IProjectVariables.CALL_DATA, IProjectVariables.CALL_DATA_FIELD_APPLICATION_NAME).getStringValue();
					strPropKey = strApplicationName+Constants.HYPEN+ivrCspInfo.getPreLang()+Constants.UNDERSCORE+Constants.PROPERTY_FILE_PATH;
					appProperties = (AppProperties) mySession.getProperty(Constants.IvrPropertyInstance);
					strPropertyFilePath = appProperties.getIVRProp(strPropKey);
					
					if((strPropertyFilePath != "N")||(strPropertyFilePath != null)){
						mySession.getVariableField(IProjectVariables.DMPROPERTIES, IProjectVariables.DMPROPERTIES_FIELD_CONFIG_FILE_PATH).setValue(strPropertyFilePath);	
						mySession.setCurrentLanguage(ivrCspInfo.getPreLang());
					}
						
					
					mySession.getVariableField(IProjectVariables.CUSTOMER_PROFILE, IProjectVariables.CUSTOMER_PROFILE_FIELD_PREF_LANGUAGE).setValue(ivrCspInfo.getPreLang());
				}
					
				else
					mySession.getVariableField(IProjectVariables.CUSTOMER_PROFILE, IProjectVariables.CUSTOMER_PROFILE_FIELD_PREF_LANGUAGE).setValue("NA");
				
				if(ivrCspInfo.getHnipre()!=null)
					mySession.getVariableField(IProjectVariables.CUSTOMER_PROFILE, IProjectVariables.CUSTOMER_PROFILE_FIELD_HNIPOS).setValue(ivrCspInfo.getHnipre());
				else
					mySession.getVariableField(IProjectVariables.CUSTOMER_PROFILE, IProjectVariables.CUSTOMER_PROFILE_FIELD_HNIPOS).setValue("NA");
				
				if(ivrCspInfo.getHnipre() != null){
					
					if((ivrCspInfo.getHnipre()).contains("HNIPOS"))
						mySession.getVariableField(IProjectVariables.FLAG, IProjectVariables.FLAG_FIELD_IS_HNICALLER).setValue(Constants.Yes);
						
				}
				
			}else{
				mySession.getVariableField(IProjectVariables.FLAG, IProjectVariables.FLAG_FIELD_IS_LINK_DOWN).setValue(Constants.Yes);
			}*/
			
		} catch (Exception e) {
			mySession.getVariableField(IProjectVariables.FLAG, IProjectVariables.FLAG_FIELD_IS_LINK_DOWN).setValue(Constants.Yes);
			PrintStackTrace.PrintException(e);
			info.writeln(ITraceInfo.TRACE_LEVEL_ERROR, "Exception:"+e.getMessage());
		}
		
		
	}
	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2015-APR-13  03:47:40 PM
	 */
	public FetchCustomerProfile() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2015-NOV-08  05:50:17 PM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = null;
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2015-NOV-08  05:50:17 PM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2015-NOV-08  05:50:17 PM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition1", "Flag:isLinkDown", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "Constants:yes", true).setDebugId(6206)).evaluate(mySession)) {
			actions = new java.util.ArrayList(1);
			actions.add(new com.avaya.sce.runtime.Next("SetLinkDown", "LinkDown").setDebugId(6207));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

		} else {

			if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition2", "Flag:isKDMHardcoded", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "Constants:yes", true).setDebugId(6209)).evaluate(mySession)) {
				actions = new java.util.ArrayList(2);
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("CallData:transferReasonCode", "TR_0132", true).setDebugId(6210));
				actions.add(new com.avaya.sce.runtime.Next("SetTransferData", "Transfer").setDebugId(6211));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			}


			if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition3", "Flag:isCSPMHardcoded", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "Constants:yes", true).setDebugId(6212)).evaluate(mySession)) {
				actions = new java.util.ArrayList(1);
				actions.add(new com.avaya.sce.runtime.Next("Initialize_MN_0003", "SelectLanguage").setDebugId(6213));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			} else {
				actions = new java.util.ArrayList(1);
				actions.add(new com.avaya.sce.runtime.Next("NotAuthorised_PA_0104", "Disconnect").setDebugId(6215));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;
			}

		}


		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
}
