package flow.subflow.BuyThePack;

import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;
import com.servion.util.AppConstant;

import flow.IProjectVariables;

/**
 * This servlet is the exit point of a subflow.  The base class handles
 * the logic for forwarding to the next servlet.
 * Last generated by Orchestration Designer at: 2015-MAR-15  02:57:46 PM
 */
public class agent extends com.avaya.sce.runtime.SubflowReturn {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2015-MAR-15  02:57:46 PM
	 */
	public agent() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}
	
	@Override
	public void requestBegin(SCESession mySession) {
		
		mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_INFO,"RCV Flag reset :");
		mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_RCVFLAG).setValue(AppConstant.FALSE);
	}
}
